use crate::{Error,Result,config,util};
use serde_json::{Value,json};
use sha2::{Digest,Sha256};
use std::{collections::BTreeSet,path::Path};

#[derive(Clone,Debug,PartialEq,Eq)]
pub struct Prefix { pub a:String,pub b:String,pub c:String }
pub fn hash(b:&[u8])->String { format!("{:x}",Sha256::digest(b))[..16].into() }
pub fn estimate(b:&[u8])->u64 { let n=b.iter().filter(|x|**x>=128).count() as u64; ((b.len() as u64-n)+2*n).div_ceil(4)+8 }
const B:usize=16*1024*1024;const N:usize=100000;
pub(crate) fn bounded(v:&Value,max:usize)->Result<()>{fn bump(n:&mut usize,x:usize,m:usize)->Result<()>{*n=n.checked_add(x).filter(|n|*n<=m).ok_or_else(||Error::new("assembly JSON byte budget exceeded"))?;Ok(())}fn strn(s:&str,n:&mut usize,m:usize)->Result<()>{bump(n,2,m)?;for c in s.chars(){bump(n,match c{'"'|'\\'|'\u{8}'|'\u{c}'|'\n'|'\r'|'\t'=>2,c if c<' '=>6,c=>c.len_utf8()},m)?;}Ok(())}fn go(v:&Value,d:usize,n:&mut usize,k:&mut usize,m:usize)->Result<()>{if d>128||*k>=N{return Err(Error::new("assembly JSON depth/node budget exceeded"))}*k+=1;match v{Value::String(s)=>strn(s,n,m)?,Value::Array(a)=>{bump(n,2+a.len().saturating_sub(1),m)?;for v in a{go(v,d+1,n,k,m)?;}},Value::Object(a)=>{bump(n,2+a.len().saturating_sub(1),m)?;for(s,v)in a{strn(s,n,m)?;bump(n,1,m)?;go(v,d+1,n,k,m)?;}},Value::Null=>bump(n,4,m)?,Value::Bool(x)=>bump(n,if *x{4}else{5},m)?,Value::Number(x)=>bump(n,x.to_string().len(),m)?}Ok(())}go(v,0,&mut 0,&mut 0,max)}
fn s<'a>(v:&'a Value,k:&str)-> &'a str {v.get(k).and_then(Value::as_str).unwrap_or("")}
fn l(v:&Value,k:&str)->Result<Vec<String>> {match v.get(k){None|Some(Value::Null)=>Ok(vec![]),Some(Value::Array(a))=>a.iter().map(|x|x.as_str().map(str::to_string).ok_or_else(||Error::new(format!("assembly {k}: expected strings")))).collect(),_=>Err(Error::new(format!("assembly {k}: expected array")))}}
fn list(a:&[String])->String { a.iter().map(|x|format!("{x}\n")).collect() }
fn text(x:&str)->String {format!("{x}\n")}
fn paths(v:&Value,k:&str,field:&str)->Result<Vec<String>> {match v.get(k){None|Some(Value::Null)=>Ok(vec![]),Some(Value::Array(a))=>a.iter().map(|x|x.as_str().or_else(||x.get(field).and_then(Value::as_str)).map(str::to_string).ok_or_else(||Error::new(format!("assembly {k}: missing {field}")))).collect(),_=>Err(Error::new(format!("assembly {k}: expected array")))}}
fn uniq(a:&[String])->Vec<String>{let mut q=BTreeSet::new();a.iter().filter(|x|q.insert((*x).clone())).cloned().collect()}
fn files(v:&Value)->Result<String>{let mut o=String::new();if let Some(a)=v.get("files"){for f in a.as_array().ok_or_else(||Error::new("assembly files: expected array"))?{let p=f.get("path").and_then(Value::as_str).ok_or_else(||Error::new("assembly file path: expected string"))?;util::rel(p)?;let t=f.get("text").and_then(Value::as_str).ok_or_else(||Error::new("assembly file text: expected string"))?;o.push_str(&format!("--- {p} ---\n{t}\n"));}}Ok(o)}
pub fn project(v:&Value)->Result<Value>{bounded(v,B)?;if !v.is_object(){return Err(Error::new("assembly configuration must be object"))}let mut o=json!({});for(k,p)in[("platform","platform"),("workspace","workspace"),("net","config.net"),("ports","ports.range"),("docs","docs")]{if let Some(x)=config::get(v,p)?{o[k]=x.clone();}}if let Some(a)=v.get("actions"){let a=a.as_object().ok_or_else(||Error::new("assembly actions: expected object"))?;let mut out=vec![];for(n,b)in a{let argv=b.get("argv").ok_or_else(||Error::new("assembly action missing argv"))?;if !argv.is_array(){return Err(Error::new("assembly action argv: expected array"));}let mut z=json!({"name":n,"argv":argv});if let Some(x)=b.get("doc"){z["doc"]=x.clone();}if let Some(x)=b.get("outputs"){if x.as_array().is_some_and(|x|!x.is_empty()){z["outputs"]=x.clone();}}out.push(z);}if !out.is_empty(){o["actions"]=json!(out);}}if let Some(t)=v.get("toolchain"){let mut a=vec![];for(n,x)in t.as_object().ok_or_else(||Error::new("toolchain must be an object"))?{let p=x.get("probe").and_then(Value::as_array).filter(|x|!x.is_empty()&&x.iter().all(Value::is_string)).ok_or_else(||Error::new("toolchain probe must be nonempty strings"))?;let mut q=json!({"name":n,"probe":p});if let Some(x)=x.get("doc"){q["doc"]=x.clone();}if let Some(r)=x.get("reading"){if r.get("probe")==Some(&json!(p)){if let Some(v)=r.get("value").filter(|x|x.is_string()||x.is_null()){q["reading"]=v.clone();}}}a.push(q);}o["toolchain"]=json!(a);}Ok(o)}
fn state(root:&Path,opts:&Value)->Result<Value>{bounded(opts,B)?;if !opts.is_object(){return Err(Error::new("assembly options must be object"))}for k in ["goal","protocol","runtime"]{if opts.get(k).is_some_and(|v|!v.is_string()){return Err(Error::new(format!("assembly option {k} must be string")))}}if let Some(v)=opts.get("state"){if !v.is_object(){return Err(Error::new("assembly state: expected object"));}return Ok(v.clone());}let cfg=config::read(root)?;let p=root.join("AGENTS.md");let policy=match std::fs::symlink_metadata(&p){Ok(m) if m.file_type().is_file()=>String::from_utf8(util::read_limited(&p,1024*1024)?).map_err(|_|Error::new("AGENTS.md is not UTF-8"))?,Ok(_)=>return Err(Error::new("AGENTS.md must be a regular file")),Err(e) if e.kind()==std::io::ErrorKind::NotFound=>String::new(),Err(_)=>return Err(Error::new("cannot read AGENTS.md"))};let c=opts.get("contract").cloned().unwrap_or(json!({}));let kind=s(&c,"kind");let goal=if kind=="investigate" {s(&c,"question")}else{c.get("goal").and_then(Value::as_str).unwrap_or(s(opts,"goal"))};let owned=if kind=="resolve"{l(&c,"conflictPaths")?}else if kind=="investigate"{paths(&c,"evidenceRequired","artifact")?}else{l(&c,"ownedPaths")?};for p in &owned{util::rel(p)?;}let deliver=if kind=="resolve"{owned.clone()}else{paths(&c,"deliverables","path")?};let assertions=paths(&c,"assertions","name")?;let evidence=if kind=="investigate"{paths(&c,"evidenceRequired","note")?}else{assertions.clone()};let holder=opts["protocol"]=="holder";let hc=if holder{crate::session::context(root,config::get(&cfg,"round.id")?.and_then(Value::as_str).unwrap_or("r1"))?}else{json!({})};let f=if kind=="implement"{owned.iter().map(|p|json!({"path":p,"text":""})).collect::<Vec<_>>()}else{vec![]};Ok(json!({"policy":policy,"system":project(&cfg)?,"codeTree":[],"goal":goal,"files":f,"commits":[],"handoff":"","task":{"goal":goal,"question":if kind=="investigate"{s(&c,"question")}else{""},"deliverables":deliver,"ownedPaths":owned,"evidenceRequired":evidence,"assertions":if kind=="investigate"{vec![]}else{assertions}},"maxSteps":opts.get("max-steps").cloned().unwrap_or(Value::Null),"distill":hc["distill"].as_str().unwrap_or(""),"recent":hc["recent"].as_str().unwrap_or(""),"runtime":s(opts,"runtime"),"signals":[],"lastStep":"","outputPaths":if kind=="investigate"{paths(&c,"evidenceRequired","artifact")?}else{vec![]}}))}
fn task(v:&Value)->Result<String>{let t=v.get("task").cloned().unwrap_or(json!({}));let mut a=vec![format!("Goal: {}",s(&t,"goal")),format!("Question: {}",s(&t,"question"))];for (k,label) in [("deliverables","Deliverables"),("ownedPaths","Write surface"),("evidenceRequired","Evidence required"),("assertions","Assertions")]{let q=l(&t,k)?;if !q.is_empty(){let q=if k=="deliverables"||k=="ownedPaths"{uniq(&q)}else{q};let mut line=format!("{label}: {}",q.join(" · "));if k=="ownedPaths"{line.push_str(" — these paths are yours, including everything under them. Do not change a single byte anywhere else, deleting included: if you find something stale, say so in your conclusion instead of clearing it away.");}a.push(line);}}if let Some(m)=v.get("maxSteps").filter(|x|!x.is_null()){let n=crate::model::positive(m,"max-steps",100000)?;a.push(format!("At most {n} steps for this task."));}a.push("When the work is done, say so in one message and stop calling tools — handing in is ending the turn.".into());a.push("The harness runs the assertions, not you.".into());a.push("Say it in English: your own words here are read by the harness, not by a person. The files you deliver are read by people — write their comments and notes in Chinese.".into());let q=l(v,"outputPaths")?;if !q.is_empty(){a.push(format!("Output paths: {}",q.join(" · ")));}Ok(a.join("\n"))}
pub fn turn_text(t:&Value)->Result<String>{bounded(t,B)?;if !t.is_object()||t.get("text").is_some_and(|v|!v.is_string()){return Err(Error::new("assembly turn/text malformed"))}if let Some(rs)=t.get("results"){let rs=rs.as_array().ok_or_else(||Error::new("assembly turn results must be array"))?;let cs=t.get("calls").and_then(Value::as_array).ok_or_else(||Error::new("assembly turn calls must be array"))?;if rs.len()!=cs.len()||rs.len()>256{return Err(Error::new("assembly turn call/result counts mismatch"))}for r in rs{if !r.is_object()||!r.get("output").is_some_and(Value::is_string)||r.get("isError").is_some_and(|v|!v.is_boolean()){return Err(Error::new("assembly turn result malformed"))}}for c in cs{if !c.is_object()||!c.get("name").is_some_and(Value::is_string){return Err(Error::new("assembly turn call malformed"))}}}let mut a=vec![];if !s(t,"text").is_empty(){a.push(format!("Model: {}",s(t,"text")));}if let Some(r)=t.get("results"){for(i,r)in r.as_array().ok_or_else(||Error::new("turn results must be an array"))?.iter().enumerate(){let name=t.get("calls").and_then(|x|x.get(i)).map(|x|s(x,"name")).unwrap_or("?");a.push(format!("Tool{} {name} (call {}):\n{}",if r.get("isError").and_then(Value::as_bool)==Some(true){" (failed)"}else{""},i+1,s(r,"output")));}}Ok(a.join("\n"))}
pub fn from_state(v:&Value,protocol:&str)->Result<Prefix>{bounded(v,B)?;for k in ["task","system"]{if v.get(k).is_some_and(|v|!v.is_object()){return Err(Error::new(format!("assembly {k} must be object")))}}if !v.is_object(){return Err(Error::new("assembly state must be object"));}for k in ["policy","goal","handoff","distill","recent","runtime","lastStep"]{if v.get(k).is_some_and(|x|!x.is_string()){return Err(Error::new(format!("assembly {k} must be string")));}}if !["subagent","holder"].contains(&protocol){return Err(Error::new(format!("unknown assembly protocol: {protocol}")));}let a=format!("{}{}{}",text(s(v,"policy")),util::canonical(v.get("system").unwrap_or(&json!({})))?,list(&l(v,"codeTree")?));let mut b=format!("{}{}{}{}",text(s(v,"goal")),files(v)?,list(&l(v,"commits")?),text(s(v,"handoff")));if protocol=="holder"{b.push_str(&text(s(v,"distill")));b.push_str(&text(s(v,"recent")));}else{b.push_str(&text(&task(v)?));}let mut r=s(v,"runtime").to_string();if let Some(ts)=v.get("turns"){for t in ts.as_array().ok_or_else(||Error::new("assembly turns: expected array"))?{let q=turn_text(t)?;if !r.is_empty(){r.push('\n');}r.push_str(&q);}}let c=format!("{}{}{}",text(&r),list(&l(v,"signals")?),text(s(v,"lastStep")));if a.len().checked_add(b.len()).and_then(|n|n.checked_add(c.len())).is_none_or(|n|n>B){return Err(Error::new("assembled prefix exceeds 16 MiB"));}Ok(Prefix{a,b,c})}
pub fn prefix(root:&Path,opts:&Value)->Result<Prefix>{from_state(&state(root,opts)?,opts.get("protocol").and_then(Value::as_str).unwrap_or("subagent"))}
pub fn initial_state(root:&Path,opts:&Value)->Result<Value>{state(root,opts)}
fn rd(x:&str)->Value{json!({"hash":hash(x.as_bytes()),"bytes":x.len()})}
pub fn assemble(root:&Path,writer:&str,opts:&Value)->Result<Value>{util::ident(writer)?;let p=prefix(root,opts)?;let protocol=opts.get("protocol").and_then(Value::as_str).unwrap_or("subagent");let mut divergence=Value::Null;if let Some(x)=opts.get("against").and_then(Value::as_str){let q=from_state(&state(root,opts)?,x)?;let u=format!("{}{}{}",p.a,p.b,p.c);let w=format!("{}{}{}",q.a,q.b,q.c);let at=u.bytes().zip(w.bytes()).position(|(a,b)|a!=b).or_else(||(u.len()!=w.len()).then_some(u.len().min(w.len())));divergence=json!({"against":x,"at":at.map(|x|x as i64).unwrap_or(-1)});}Ok(json!({"protocol":protocol,"version":"s6-1","agent":writer,"segments":if protocol=="holder"{12}else{11},"toolCatalog":crate::tools::catalog().as_array().map(Vec::len).unwrap_or(0),"zones":{"A":rd(&p.a),"B":rd(&p.b),"C":rd(&p.c)},"ab":rd(&format!("{}{}",p.a,p.b)),"whole":rd(&format!("{}{}{}",p.a,p.b,p.c)),"firstDivergence":divergence,"violations":constraints(&p,opts)?}))}
fn abs(x:&str)->Option<String>{let b=x.as_bytes();let valid=|c:u8|c.is_ascii_alphanumeric()||b"._-".contains(&c);for i in 0..b.len(){if b[i]!=b'/'||(i>0&&!b" \t\"'`(=:,[]-\n\r".contains(&b[i-1])){continue;}let mut j=i+1;while j<b.len()&&valid(b[j]){j+=1;}if j==i+1||j>=b.len()||b[j]!=b'/'{continue;}j+=1;let at=j;while j<b.len()&&(valid(b[j])||b[j]==b'/'){j+=1;}if j>at{return Some(x[i..j].into());}}None}
fn signal(x:&str)->bool{let mut at=0;while let Some(i)=x[at..].find("digest"){let mut t=&x[at+i+6..];if let Some(q)=t.strip_prefix('"'){t=q;}t=t.trim_start_matches([' ','\t']);if t.starts_with([':', '=']){return true;}at+=i+6;}false}
pub fn constraints(p:&Prefix,opts:&Value)->Result<Vec<Value>>{let mut out=vec![];for(z,x)in[("A",&p.a),("B",&p.b),("C",&p.c)]{if let Some(q)=abs(x){out.push(json!({"kind":"materialized","where":z,"detail":format!("absolute path present: {q}")}));}if signal(x){out.push(json!({"kind":"signal","where":z,"detail":"raw Signal digest field present"}));}}let mut host=[0i8;256];let host=if unsafe{libc::gethostname(host.as_mut_ptr(),host.len())}==0{let bytes=host.iter().take_while(|x|**x!=0).map(|x|*x as u8).collect::<Vec<_>>();String::from_utf8(bytes).unwrap_or_default()}else{String::new()};if !host.is_empty()&&p.a.contains(&host){out.push(json!({"kind":"env","where":"A","detail":"host name present"}));}let pid=std::process::id().to_string();if p.a.match_indices(&pid).any(|(i,_)|{let b=p.a.as_bytes();(i==0||!b[i-1].is_ascii_digit())&&(i+pid.len()==b.len()||!b[i+pid.len()].is_ascii_digit())}){out.push(json!({"kind":"env","where":"A","detail":"process identity present"}));}if let Some(prev)=opts.get("previous"){let c=prev.get("C").and_then(Value::as_str).ok_or_else(||Error::new("previous prefix requires C string"))?;if !p.c.starts_with(c){out.push(json!({"kind":"append-only","where":"C","detail":"prior C is not a prefix of current C"}));}}Ok(out)}
