use crate::{Error,Result,util};use serde_json::{Value,json};use std::path::{Path,PathBuf};
pub const KEYS:&[&str]=&["actions","ports","boundary","platform","round","config","docs","workspace","credentials","toolchain"];
pub fn system_dir()->Result<PathBuf>{if let Some(x)=std::env::var_os("FUGUE_SYSTEM_DIR"){if !x.is_empty(){return Ok(PathBuf::from(x))}}std::env::var_os("HOME").map(|x|PathBuf::from(x).join(".fugue")).ok_or_else(||Error::new("HOME missing for system configuration"))}
fn one(p:&Path)->Result<Value>{match std::fs::symlink_metadata(p){Err(e) if e.kind()==std::io::ErrorKind::NotFound=>return Ok(json!({})),Err(e)=>return Err(e.into()),Ok(m) if !m.is_file()=>return Err(Error::new("configuration must be a regular file")),_=>{}}let b=util::read_limited(p,1024*1024)?;if b.iter().all(u8::is_ascii_whitespace){return Ok(json!({}))}let v=util::json(&b)?;validate(&v)?;Ok(v)}
fn validate(v:&Value)->Result<()>{let o=v.as_object().ok_or_else(||Error::new("configuration root must be an object"))?;if o.keys().any(|k|!KEYS.contains(&k.as_str())){return Err(Error::new(format!("unknown configuration top-level key; allowed: {}",KEYS.join(", "))))}Ok(())}
fn mix(a:&mut Value,b:Value){match (a,b){(Value::Object(a),Value::Object(b))=>{for (k,v) in b{if let Some(w)=a.get_mut(&k){mix(w,v)}else{a.insert(k,v);}}},(a,b)=>*a=b}}
pub fn read(r:&Path)->Result<Value>{let mut a=one(&system_dir()?.join("config"))?;mix(&mut a,one(&r.join(".fugue/config"))?);Ok(a)}
fn parts(k:&str)->Result<Vec<&str>>{if k.is_empty()||k.len()>4096||k.split('.').count()>128||k.split('.').any(|x|x.is_empty()||x.chars().any(char::is_control)||["__proto__","constructor","prototype"].contains(&x)){return Err(Error::usage("invalid configuration key"))}Ok(k.split('.').collect())}
pub fn get<'a>(v:&'a Value,k:&str)->Result<Option<&'a Value>>{let mut a=v;for s in parts(k)?{match a.as_object().and_then(|x|x.get(s)){Some(x)=>a=x,None=>return Ok(None)}}Ok(Some(a))}
pub fn set(r:&Path,k:&str,b:&str,s:bool)->Result<Value>{if b.len()>1024*1024{return Err(Error::usage("configuration input byte budget exceeded"))}let a=parts(k)?;if !KEYS.contains(&a[0]){return Err(Error::usage("unknown configuration top-level key"))}if !s&&!r.is_dir(){return Err(Error::new("workspace root does not exist"))}let d=if s{system_dir()?}else{r.join(".fugue")};let _l=util::FileLock::take(&d.join("config.lock"))?;let p=d.join("config");let mut v=one(&p)?;let old=get(&v,k)?.cloned();let n=match util::json(b.as_bytes()){Ok(v)=>v,Err(e) if b.trim_start().starts_with(['{','['])=>return Err(e),Err(_)=>Value::String(b.into())};let mut q=&mut v;for x in &a[..a.len()-1]{let o=q.as_object_mut().ok_or_else(||Error::new("intermediate configuration key is not an object"))?;q=o.entry(x.to_string()).or_insert_with(||json!({}));if !q.is_object(){return Err(Error::new("intermediate configuration key is not an object"))}}q.as_object_mut().ok_or_else(||Error::new("configuration container invalid"))?.insert(a[a.len()-1].into(),n.clone());validate(&v)?;let prev=match std::fs::symlink_metadata(&p){Ok(_)=>Some(util::read_limited(&p,1024*1024)?),Err(e) if e.kind()==std::io::ErrorKind::NotFound=>None,Err(e)=>return Err(e.into())};let h=d.join("config-history");let mut hb=match std::fs::symlink_metadata(&h){Ok(_)=>util::read_limited(&h,16*1024*1024)?,Err(e) if e.kind()==std::io::ErrorKind::NotFound=>Vec::new(),Err(e)=>return Err(e.into())};let mut ch=json!({"at":util::timestamp()?,"key":k,"new":n});if let Some(o)=old.clone(){ch["old"]=o;}let l=serde_json::to_vec(&ch)?;if hb.len().checked_add(l.len()+1).is_none_or(|n|n>16*1024*1024){return Err(Error::new("configuration history byte budget exceeded"))}hb.extend(l);hb.push(b'\n');let mut out=util::json_pretty_bounded(&v,1024*1024-1)?;out.push(b'\n');if out.len()>1024*1024{return Err(Error::new("serialized configuration byte budget exceeded"))}util::json(&out)?;util::atomic_write(&p,&out)?;if let Err(e)=util::atomic_write(&h,&hb){match prev{Some(b)=>util::atomic_write(&p,&b)?,None=>std::fs::remove_file(&p)?}return Err(e)}Ok(json!({"key":k,"old":old,"new":n,"system":s}))}
#[cfg(test)]mod tests{use super::*;#[test]fn nested_merge_and_closed_keys(){let mut a=json!({"actions":{"a":{"argv":["x"]}},"round":{"id":"r1"}});mix(&mut a,json!({"actions":{"b":{"argv":["y"]}},"round":{"id":"r2"}}));assert_eq!(get(&a,"round.id").unwrap(),Some(&json!("r2")));assert!(get(&a,"round..id").is_err());assert!(validate(&json!({"typo":true})).is_err());}#[test]fn set_and_history(){let d=tempfile::tempdir().unwrap();set(d.path(),"round.id","r2",false).unwrap();assert_eq!(one(&d.path().join(".fugue/config")).unwrap()["round"]["id"],"r2");assert!(set(d.path(),"round.id.x","5",false).is_err());let h=util::read_limited(&d.path().join(".fugue/config-history"),1024).unwrap();assert_eq!(h.iter().filter(|&&x|x==b'\n').count(),1);}}
