use crate::{Error,Result,util};
use serde::{Serialize,Deserialize,Deserializer,de::{Visitor,MapAccess,SeqAccess}};
use serde_json::{Value,Map,json};
use std::{collections::BTreeSet,ffi::CString,fs::File,io::{Read,Write,Seek,SeekFrom},os::fd::{AsRawFd,FromRawFd},path::{Path,PathBuf},sync::atomic::{AtomicU64,Ordering}};
#[derive(Clone,Debug,PartialEq,Serialize)]pub struct Row{pub seq:u64,pub writer:String,pub event:Value}
fn e(x:impl std::fmt::Display)->Error{Error::new(x.to_string())}
fn cs(x:&str)->Result<CString>{CString::new(x).map_err(e)}
fn op(d:&File,n:&str,f:i32,m:u32)->Result<File>{let n=cs(n)?;let x=unsafe{libc::openat(d.as_raw_fd(),n.as_ptr(),f|libc::O_CLOEXEC|libc::O_NOFOLLOW|libc::O_NONBLOCK,m as libc::mode_t)};if x<0{return Err(e(std::io::Error::last_os_error()))}Ok(unsafe{File::from_raw_fd(x)})}
fn root(p:&Path)->Result<File>{let p=std::fs::canonicalize(p).map_err(e)?;let p=cs(p.to_str().ok_or_else(||e("non-UTF-8 root"))?)?;let x=unsafe{libc::open(p.as_ptr(),libc::O_RDONLY|libc::O_CLOEXEC|libc::O_DIRECTORY|libc::O_NOFOLLOW)};if x<0{return Err(e(std::io::Error::last_os_error()))}Ok(unsafe{File::from_raw_fd(x)})}
fn sub(d:&File,n:&str,mk:bool)->Result<Option<File>>{let n0=cs(n)?;let x=unsafe{libc::openat(d.as_raw_fd(),n0.as_ptr(),libc::O_RDONLY|libc::O_CLOEXEC|libc::O_DIRECTORY|libc::O_NOFOLLOW)};if x>=0{return Ok(Some(unsafe{File::from_raw_fd(x)}))}let z=std::io::Error::last_os_error();if z.kind()!=std::io::ErrorKind::NotFound{return Err(e(format!("unsafe journal directory {n}: {z}")))}if !mk{return Ok(None)}if unsafe{libc::mkdirat(d.as_raw_fd(),n0.as_ptr(),0o700)}!=0&&std::io::Error::last_os_error().kind()!=std::io::ErrorKind::AlreadyExists{return Err(e(std::io::Error::last_os_error()))}op(d,n,libc::O_RDONLY|libc::O_DIRECTORY,0).map(Some)}
fn dir(p:&Path,w:&str,mk:bool)->Result<Option<(File,String)>>{util::ident(w)?;let mut f=root(p)?;let parts:Vec<_>=w.split('/').collect();for n in [".fugue","log"].into_iter().chain(parts[..parts.len()-1].iter().copied()){f=match sub(&f,n,mk)?{Some(x)=>x,None=>return Ok(None)}}Ok(Some((f,parts[parts.len()-1].into())))}
fn limited(f:&File)->Result<Vec<u8>>{limited_n(f,util::MAX_BYTES)}
fn limited_n(f:&File,n:usize)->Result<Vec<u8>>{use std::os::unix::fs::MetadataExt;let m=f.metadata().map_err(e)?;if !m.is_file()||m.nlink()!=1||m.len()>n as u64{return Err(e("journal must be a bounded regular file"))}let mut b=Vec::new();f.take((n+1)as u64).read_to_end(&mut b).map_err(e)?;if b.len()>n{return Err(e("journal exceeds byte limit"))}Ok(b)}
struct J(Value);impl<'de>Deserialize<'de> for J{fn deserialize<D:Deserializer<'de>>(d:D)->std::result::Result<Self,D::Error>{struct V;impl<'de>Visitor<'de> for V{type Value=J;fn expecting(&self,f:&mut std::fmt::Formatter)->std::fmt::Result{write!(f,"bounded JSON without duplicate object keys")}fn visit_bool<E:serde::de::Error>(self,v:bool)->std::result::Result<J,E>{Ok(J(v.into()))}fn visit_i64<E:serde::de::Error>(self,v:i64)->std::result::Result<J,E>{Ok(J(v.into()))}fn visit_u64<E:serde::de::Error>(self,v:u64)->std::result::Result<J,E>{Ok(J(v.into()))}fn visit_f64<E:serde::de::Error>(self,v:f64)->std::result::Result<J,E>{serde_json::Number::from_f64(v).map(|x|J(Value::Number(x))).ok_or_else(||E::custom("non-finite number"))}fn visit_str<E:serde::de::Error>(self,v:&str)->std::result::Result<J,E>{Ok(J(v.into()))}fn visit_string<E:serde::de::Error>(self,v:String)->std::result::Result<J,E>{Ok(J(v.into()))}fn visit_unit<E:serde::de::Error>(self)->std::result::Result<J,E>{Ok(J(Value::Null))}fn visit_none<E:serde::de::Error>(self)->std::result::Result<J,E>{Ok(J(Value::Null))}fn visit_seq<A:SeqAccess<'de>>(self,mut a:A)->std::result::Result<J,A::Error>{let mut v=Vec::new();while let Some(J(x))=a.next_element()?{if v.len()>=util::MAX_EVENTS{return Err(serde::de::Error::custom("too many JSON elements"))}v.push(x)}Ok(J(Value::Array(v)))}fn visit_map<A:MapAccess<'de>>(self,mut a:A)->std::result::Result<J,A::Error>{let mut v=Map::new();while let Some(k)=a.next_key::<String>()?{if v.contains_key(&k){return Err(serde::de::Error::custom("duplicate JSON key"))}if v.len()>=util::MAX_EVENTS{return Err(serde::de::Error::custom("too many JSON fields"))}let J(x)=a.next_value()?;v.insert(k,x);}Ok(J(Value::Object(v)))}}d.deserialize_any(V)}}
fn integer(v:&Value)->Option<u64>{v.as_u64().filter(|x|*x<=9007199254740991).or_else(||v.as_f64().filter(|x|x.is_finite()&&*x>=0.0&&*x<=9007199254740991.0&&x.fract()==0.0).map(|x|x as u64))}
fn parse(w:&str,b:&[u8])->Result<(Vec<Row>,usize)>{let end=b.iter().rposition(|x|*x==b'\n').map_or(0,|x|x+1);let mut out=Vec::new();for (i,b)in b[..end].split(|x|*x==b'\n').enumerate(){if b.is_empty(){continue}let J(v)=serde_json::from_slice(b).map_err(|x|e(format!("corrupt journal {w} line {}: {x}",i+1)))?;let mut m=v.as_object().cloned().ok_or_else(||e("journal row is not an object"))?;let seq=m.remove("seq").and_then(|x|integer(&x)).filter(|x|*x>0&&*x<=9007199254740991).ok_or_else(||e("invalid journal seq"))?;let writer=m.remove("writer").and_then(|x|x.as_str().map(str::to_owned)).ok_or_else(||e("invalid journal writer"))?;if writer!=w{return Err(e("journal writer does not match file name"))}let crc=m.remove("crc").and_then(|x|x.as_str().map(str::to_owned)).filter(|x|x.len()==8&&x.bytes().all(|x|x.is_ascii_hexdigit())).ok_or_else(||e("invalid journal crc"))?;let t=m.get("t").and_then(Value::as_str).filter(|x|!x.is_empty()).ok_or_else(||e("invalid event type"))?;if t.len()>4096{return Err(e("oversized event type"))}let mut z=m.clone();z.insert("seq".into(),seq.into());z.insert("writer".into(),writer.clone().into());let want=format!("{:08x}",crc32fast::hash(util::canonical(&Value::Object(z))?.as_bytes()));if !want.eq_ignore_ascii_case(&crc){return Err(e(format!("corrupt journal {w} line {}: CRC mismatch",i+1)))}if seq!=(out.len() as u64)+1{return Err(e(format!("corrupt journal {w}: sequence must start at 1 and be contiguous")))}if out.len()>=util::MAX_EVENTS{return Err(e("too many journal events"))}out.push(Row{seq,writer,event:Value::Object(m)})}Ok((out,end))}
pub fn read(p:&Path,w:&str)->Result<Vec<Row>>{Ok(loaded(p,w,util::MAX_BYTES)?.0)}
fn loaded(p:&Path,w:&str,nmax:usize)->Result<(Vec<Row>,usize)>{let Some((d,n))=dir(p,w,false)?else{return Ok((vec![],0))};let n=format!("{n}.jsonl");let f=match op(&d,&n,libc::O_RDONLY,0){Ok(x)=>x,Err(x)=>{let n0=cs(&n)?;let mut st=std::mem::MaybeUninit::<libc::stat>::uninit();if unsafe{libc::fstatat(d.as_raw_fd(),n0.as_ptr(),st.as_mut_ptr(),libc::AT_SYMLINK_NOFOLLOW)}<0&&std::io::Error::last_os_error().kind()==std::io::ErrorKind::NotFound{return Ok((vec![],0))}return Err(x)}};let bytes=limited_n(&f,nmax)?;Ok((parse(w,&bytes)?.0,bytes.len()))}
pub fn merged(p:&Path)->Result<Vec<Row>>{fn walk(d:&File,prefix:&str,out:&mut BTreeSet<String>,depth:usize,count:&mut usize,bytes:&mut usize)->Result<()>{if depth>128{return Err(e("journal directory depth exceeded"))}let path=format!("/proc/self/fd/{}",d.as_raw_fd());for x in std::fs::read_dir(path).map_err(e)?{let x=x.map_err(e)?;let n=x.file_name().into_string().map_err(|_|e("non-UTF-8 journal file name"))?;*count=count.checked_add(1).filter(|n|*n<=util::MAX_EVENTS).ok_or_else(||e("journal storage entry budget exceeded"))?;*bytes=bytes.checked_add(n.len()).filter(|n|*n<=util::MAX_BYTES).ok_or_else(||e("journal storage name budget exceeded"))?;let t=x.file_type().map_err(e)?;if t.is_symlink(){return Err(e("symlinks are forbidden in journal storage"))}if t.is_dir(){let f=sub(d,&n,false)?.ok_or_else(||e("journal directory disappeared"))?;walk(&f,&format!("{prefix}{n}/"),out,depth+1,count,bytes)?}else if let Some(n)=n.strip_suffix(".jsonl"){let w=format!("{prefix}{n}");util::ident(&w)?;out.insert(w);if out.len()>util::MAX_EVENTS{return Err(e("too many writers"))}}}Ok(())}let mut d=root(p)?;for n in [".fugue","log"]{d=match sub(&d,n,false)?{Some(x)=>x,None=>return Ok(vec![])}}let mut w=BTreeSet::new();walk(&d,"",&mut w,0,&mut 0,&mut 0)?;let mut v=Vec::new();let mut bytes=0usize;for w in w{let(rows,n)=loaded(p,&w,util::MAX_BYTES-bytes)?;bytes=bytes.checked_add(n).filter(|n|*n<=util::MAX_BYTES).ok_or_else(||e("merged journal byte budget exceeded"))?;v.extend(rows);if v.len()>util::MAX_EVENTS{return Err(e("too many merged events"))}}v.sort_by(|a,b|a.seq.cmp(&b.seq).then(a.writer.encode_utf16().cmp(b.writer.encode_utf16())));Ok(v)}
fn boot()->Option<String>{std::fs::read_to_string("/proc/sys/kernel/random/boot_id").ok().map(|x|x.trim().into())}
fn start(p:u32)->Option<u64>{let s=std::fs::read_to_string(format!("/proc/{p}/stat")).ok()?;s[s.rfind(')')?+1..].split_whitespace().nth(19)?.parse().ok()}
fn stale(v:&Value)->bool{let Some(b)=boot()else{return false};let Some(vb)=v.get("boot").and_then(Value::as_str)else{return false};let Some(p)=v.get("pid").and_then(Value::as_u64).filter(|x|*x>0&&*x<=i32::MAX as u64)else{return false};let Some(t)=v.get("start").and_then(Value::as_u64)else{return false};if b!=vb{return true}match start(p as u32){Some(x)=>x!=t,None=>{let z=unsafe{libc::kill(p as i32,0)};z<0&&std::io::Error::last_os_error().raw_os_error()==Some(libc::ESRCH)}}}
fn same(d:&File,n:&str,f:&File)->Result<bool>{use std::os::unix::fs::MetadataExt;let mut st=std::mem::MaybeUninit::<libc::stat>::uninit();let n=cs(n)?;if unsafe{libc::fstatat(d.as_raw_fd(),n.as_ptr(),st.as_mut_ptr(),libc::AT_SYMLINK_NOFOLLOW)}<0{return Ok(false)}let st=unsafe{st.assume_init()};let m=f.metadata().map_err(e)?;Ok(st.st_ino==m.ino()&&st.st_dev==m.dev())}
fn unlink(d:&File,n:&str)->Result<()>{let n=cs(n)?;if unsafe{libc::unlinkat(d.as_raw_fd(),n.as_ptr(),0)}<0{return Err(e(std::io::Error::last_os_error()))}Ok(())}
static C:AtomicU64=AtomicU64::new(0);
/// Hold this guard for the entire writer transaction. Use append_locked with
/// this guard, never append (which would reacquire the same non-reentrant lock).
/// Reads take no locks and cannot repair files. Drop releases only its own inode.
pub struct Lock{pub writer:String,pub root:PathBuf,d:File,f:File,n:String,other:Option<Box<Lock>>}
impl Lock{pub fn take(p:&Path,w:&str)->Result<Self>{let mut l=Self::one(p,w,w)?;if let Some((a,_))=w.rsplit_once('/'){let z=format!("{a}/{w}");l.other=Some(Box::new(Self::one(p,w,&z)?));}Ok(l)}fn one(p:&Path,w:&str,z:&str)->Result<Self>{let root=std::fs::canonicalize(p).map_err(e)?;let(d,n)=dir(&root,z,true)?.ok_or_else(||e("cannot create journal directory"))?;let n=format!("{n}.lock");let tmp=format!("{n}.tmp-{}-{}",std::process::id(),C.fetch_add(1,Ordering::Relaxed));let mut f=op(&d,&tmp,libc::O_WRONLY|libc::O_CREAT|libc::O_EXCL,0o600)?;let v=json!({"v":1,"writer":w,"pid":std::process::id(),"start":start(std::process::id()).unwrap_or(0),"boot":boot().unwrap_or_default(),"t":std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_err(e)?.as_millis() as u64});let result=(||{f.write_all(serde_json::to_string(&v).map_err(e)?.as_bytes()).map_err(e)?;f.sync_all().map_err(e)?;if unsafe{libc::flock(f.as_raw_fd(),libc::LOCK_EX|libc::LOCK_NB)}!=0{return Err(e("cannot hold writer lock"))}for _ in 0..8{let tn=cs(&tmp)?;let nn=cs(&n)?;if unsafe{libc::linkat(d.as_raw_fd(),tn.as_ptr(),d.as_raw_fd(),nn.as_ptr(),0)}==0{return Ok(())}if std::io::Error::last_os_error().kind()!=std::io::ErrorKind::AlreadyExists{return Err(e("cannot publish writer lock"))}let old=match op(&d,&n,libc::O_RDONLY,0){Ok(x)=>x,Err(_)=>return Err(e("writer lock is unsafe or unreadable"))};if unsafe{libc::flock(old.as_raw_fd(),libc::LOCK_EX|libc::LOCK_NB)}!=0{return Err(e(format!("writer {w} is already locked")))}if old.metadata().map_err(e)?.len()>4096{return Err(e("writer lock record exceeds budget"))}let z=limited(&old)?;let oldv:Value=serde_json::from_slice(&z).map_err(|_|e("writer lock is malformed; refusing takeover"))?;if oldv.get("v").and_then(Value::as_u64)!=Some(1)||oldv.get("writer").and_then(Value::as_str)!=Some(w){return Err(e("writer lock owner record mismatch"))}if !stale(&oldv){return Err(e(format!("writer {w} is already locked or owner cannot be proven dead")))}if same(&d,&n,&old)?{unlink(&d,&n)?;}}Err(e("writer lock takeover contention"))})();let _=unlink(&d,&tmp);result?;if let Err(x)=d.sync_all(){if same(&d,&n,&f).unwrap_or(false){let _=unlink(&d,&n);}return Err(e(x))}Ok(Self{writer:w.into(),root,d,f,n,other:None})}}
impl Drop for Lock{fn drop(&mut self){if same(&self.d,&self.n,&self.f).unwrap_or(false){let _=unlink(&self.d,&self.n);let _=self.d.sync_all();}let _=unsafe{libc::flock(self.f.as_raw_fd(),libc::LOCK_UN)};}}
fn encode(w:&str,n:u64,v:Value)->Result<Vec<u8>>{let mut m=v.as_object().cloned().ok_or_else(||e("event must be an object"))?;if ["seq","writer","crc"].iter().any(|x|m.contains_key(*x))||!m.get("t").and_then(Value::as_str).is_some_and(|x|!x.is_empty()&&x.len()<=4096){return Err(e("event contains reserved fields or invalid type"))}m.insert("seq".into(),n.into());m.insert("writer".into(),w.into());let crc=format!("{:08x}",crc32fast::hash(util::canonical(&Value::Object(m.clone()))?.as_bytes()));m.insert("crc".into(),crc.into());let mut b=serde_json::to_vec(&m).map_err(e)?;b.push(b'\n');Ok(b)}
pub fn append(p:&Path,w:&str,v:Value)->Result<u64>{util::ident(w)?;encode(w,1,v.clone())?;let l=Lock::take(p,w)?;append_locked(&l,v)}
pub fn append_locked(l:&Lock,v:Value)->Result<u64>{append_many_locked(l,vec![v])}
/// All rows are validated before writing. One write buffer and fsync preserve
/// order; a power loss can leave a complete prefix and an ignored partial tail.
pub fn append_many_locked(l:&Lock,v:Vec<Value>)->Result<u64>{if v.is_empty(){return Err(e("empty journal append"))}for x in &v{encode(&l.writer,1,x.clone())?;}if !same(&l.d,&l.n,&l.f)?||l.other.as_ref().is_some_and(|x|!same(&x.d,&x.n,&x.f).unwrap_or(false)){return Err(e("writer lock ownership changed"))}let n=l.n.strip_suffix(".lock").ok_or_else(||e("invalid writer lock"))?;let mut f=op(&l.d,&format!("{n}.jsonl"),libc::O_RDWR|libc::O_CREAT|libc::O_APPEND,0o600)?;let b=limited(&f)?;let(rows,end)=parse(&l.writer,&b)?;let first=rows.len() as u64;let count=v.len() as u64;let mut buf=Vec::new();for (i,v) in v.into_iter().enumerate(){let n=first.checked_add(i as u64+1).filter(|x|*x<=9007199254740991&&*x<=util::MAX_EVENTS as u64).ok_or_else(||e("journal sequence exhausted"))?;buf.extend(encode(&l.writer,n,v)?);if end.checked_add(buf.len()).is_none_or(|x|x>util::MAX_BYTES){return Err(e("journal byte limit exceeded"))}}if end!=b.len(){f.set_len(end as u64).map_err(e)?;f.seek(SeekFrom::End(0)).map_err(e)?;}f.write_all(&buf).map_err(e)?;f.sync_all().map_err(e)?;l.d.sync_all().map_err(e)?;Ok(first+count)}

/// Validate capacity, sequence, CRC and envelope before a coupled ref mutation.
pub fn preflight_locked(l:&Lock,v:&[Value])->Result<()>{if !same(&l.d,&l.n,&l.f)?||l.other.as_ref().is_some_and(|x|!same(&x.d,&x.n,&x.f).unwrap_or(false)){return Err(e("writer lock ownership changed"))}let rows=read(&l.root,&l.writer)?;let mut bytes=0usize;for(i,x)in v.iter().enumerate(){let seq=(rows.len() as u64).checked_add(i as u64+1).filter(|x|*x<=util::MAX_EVENTS as u64&&*x<=9007199254740991).ok_or_else(||e("journal sequence exhausted"))?;bytes=bytes.checked_add(encode(&l.writer,seq,x.clone())?.len()).ok_or_else(||e("journal capacity overflow"))?;}let n=l.n.strip_suffix(".lock").ok_or_else(||e("invalid writer lock"))?;let name=format!("{n}.jsonl");let size=match op(&l.d,&name,libc::O_RDWR|libc::O_APPEND,0){Ok(f)=>parse(&l.writer,&limited(&f)?)?.1,Err(x)=>{let n0=cs(&name)?;let mut st=std::mem::MaybeUninit::<libc::stat>::uninit();if unsafe{libc::fstatat(l.d.as_raw_fd(),n0.as_ptr(),st.as_mut_ptr(),libc::AT_SYMLINK_NOFOLLOW)}<0&&std::io::Error::last_os_error().kind()==std::io::ErrorKind::NotFound&&rows.is_empty(){0}else{return Err(x)}}};if size.checked_add(bytes).is_none_or(|x|x>util::MAX_BYTES){return Err(e("journal byte limit exceeded"))}Ok(())}
