use crate::{Error,Result,journal,util};use serde_json::{Value,json};use sha2::{Sha256,Digest};use std::{path::Path,collections::{BTreeMap,BTreeSet}};const B:usize=16*1024*1024;
fn ck(i:&str)->Result<()>{util::ident(i)?;if i.contains('/'){return Err(Error::new("session round must be one identifier segment"))}Ok(())}fn st<'a>(v:&'a Value,k:&str)->Result<&'a str>{v[k].as_str().ok_or_else(||Error::new(format!("session requires string {k}")))}fn h(s:&str)->String{format!("{:x}",Sha256::digest(s.as_bytes()))[..16].into()}
pub fn path_of(i:&str)->Result<String>{ck(i)?;Ok(format!(".fugue/session/{i}.jsonl"))}pub fn recognize(p:&str)->Result<Option<&str>>{let Some(i)=p.strip_prefix(".fugue/session/").and_then(|p|p.strip_suffix(".jsonl"))else{return Ok(None)};ck(i)?;Ok(Some(i))}
pub fn records_of(s:&str)->Result<Value>{if s.len()>B{return Err(Error::new("session projection exceeds16MiB"))}let mut records=vec![];let mut bad=vec![];for line in s.lines().filter(|s|!s.trim().is_empty()){match util::json(line.as_bytes()){Ok(v) if v["who"].is_string()&&v["text"].is_string()=>records.push(json!({"who":v["who"],"text":v["text"]})),_=>bad.push(line.to_owned())}if records.len()+bad.len()>util::MAX_EVENTS{return Err(Error::new("session record budget exceeded"))}}Ok(json!({"records":records,"bad":bad}))}
pub fn recent_of(s:&str,n:usize)->Result<String>{if n>1000{return Err(Error::new("recent session count exceeds1000"))}let v=records_of(s)?;let a=v["records"].as_array().ok_or_else(||Error::new("session records missing"))?;Ok(a.iter().skip(a.len().saturating_sub(n)).map(|v|Ok(format!("{}：{}",st(v,"who")?,st(v,"text")?))).collect::<Result<Vec<_>>>()?.join("\n"))}
fn add_record(out:&mut String,who:&str,text:&str)->Result<()>{if who.is_empty()||who.len()>256||text.len()>1024*1024||text.contains('\0'){return Err(Error::new("session role/text invalid or oversized"))}let line=format!("{{\"who\":{},\"text\":{}}}\n",serde_json::to_string(who)?,serde_json::to_string(text)?);let gap=usize::from(!out.is_empty()&&!out.ends_with('\n'));if out.len().checked_add(line.len()).and_then(|n|n.checked_add(gap)).is_none_or(|n|n>B){return Err(Error::new("session projection exceeds16MiB"))}if gap!=0{out.push('\n')}out.push_str(&line);Ok(())}
pub fn record_of(s:&str,who:&str,text:&str)->Result<String>{if s.len()>B{return Err(Error::new("session projection exceeds16MiB"))}let mut out=s.to_owned();add_record(&mut out,who,text)?;Ok(out)}
fn fold(rows:&[journal::Row],i:&str)->Result<(String,Value)>{ck(i)?;let mut archive=String::new();let mut versions=vec![];let mut previous=None::<String>;let mut distinct=BTreeMap::new();let mut receipts=BTreeSet::new();let mut ended=BTreeSet::new();for row in rows{let e=&row.event;if e["round"]!=i{continue}if ["session/message","holder/distill","say/end"].iter().any(|t|e["t"]==*t){if e.get("session").is_some(){let sid=st(e,"session")?;util::ident(sid)?;let key=if e["t"]=="session/message"{format!("session/message:{}",st(e,"role")?)}else{st(e,"t")?.into()};if !receipts.insert((sid.to_owned(),key))||ended.contains(sid){return Err(Error::new("duplicate or post-completion session receipt"))}if e["t"]=="say/end"{ended.insert(sid.to_owned());}}}if e["t"]=="session/message"{let who=match st(e,"role")?{"user"=>"人","assistant"=>"持轮者",_=>return Err(Error::new("unknown archived session role"))};add_record(&mut archive,who,st(e,"body")?)?;}else if e["t"]=="holder/distill"{let body=st(e,"body")?;let digest=st(e,"digest")?;let against=match e.get("against"){None=>None,Some(Value::String(v))=>Some(v.as_str()),_=>return Err(Error::new("holder against receipt must be a string or absent"))};if body.is_empty()||body.len()>B||body.contains('\0')||e["agent"]!="round"||h(body)!=digest||against!=previous.as_deref(){return Err(Error::new("holder version body/digest/against chain mismatch"))}let version=if let Some(n)=distinct.get(digest){*n}else{let n=distinct.len()+1;distinct.insert(digest.to_owned(),n);n};versions.push(json!({"at":versions.len()+1,"version":version,"digest":digest,"against":previous,"body":body}));previous=Some(digest.into());}}Ok((archive,json!(versions)))}
pub fn archive(root:&Path,i:&str)->Result<String>{Ok(fold(&journal::read(root,"round")?,i)?.0)}
pub fn append(root:&Path,i:&str,role:&str,text:&str)->Result<()> {let l=journal::Lock::take(root,"round")?;let old=archive(root,i)?;let who=match role{"user"=>"人","assistant"=>"持轮者",_=>return Err(Error::new("unknown session role"))};record_of(&old,who,text)?;journal::append_locked(&l,json!({"t":"session/message","round":i,"role":role,"body":text}))?;Ok(())}
pub fn versions(root:&Path,i:&str)->Result<Value>{Ok(fold(&journal::read(root,"round")?,i)?.1)}
pub fn context(root:&Path,i:&str)->Result<Value>{let(archive,versions)=fold(&journal::read(root,"round")?,i)?;let last=versions.as_array().and_then(|a|a.last());Ok(json!({"path":path_of(i)?,"records":records_of(&archive)?["records"].as_array().map(Vec::len).unwrap_or(0),"badLines":0,"recent":recent_of(&archive,3)?,"distill":last.and_then(|v|v["body"].as_str()).unwrap_or(""),"version":last.cloned().unwrap_or(Value::Null)}))}
pub fn land(root:&Path,i:&str,body:&str)->Result<Value>{if body.is_empty()||body.len()>B||body.contains('\0'){return Err(Error::new("holder understanding invalid or oversized"))}let l=journal::Lock::take(root,"round")?;let versions=versions(root,i)?;let mut e=json!({"t":"holder/distill","round":i,"agent":"round","digest":h(body),"body":body});if let Some(last)=versions.as_array().and_then(|a|a.last()){e["against"]=last["digest"].clone()}journal::append_locked(&l,e)?;Ok(context(root,i)?["version"].clone())}

pub fn append_for(root:&Path,i:&str,role:&str,text:&str,sid:&str)->Result<()>{ck(i)?;util::ident(sid)?;let who=match role{"user"=>"人","assistant"=>"持轮者",_=>return Err(Error::new("unknown session role"))};record_of("",who,text)?;let l=journal::Lock::take(root,"round")?;let rows=journal::read(root,"round")?;let old=fold(&rows,i)?.0;if let Some(e)=rows.iter().find(|e|e.event["t"]=="session/message"&&e.event["round"]==i&&e.event["session"]==sid&&e.event["role"]==role){if e.event["body"]!=text{return Err(Error::new("session archival receipt mismatch"))}return Ok(())}if rows.iter().any(|e|e.event["t"]=="say/end"&&e.event["round"]==i&&e.event["session"]==sid){return Err(Error::new("session is already complete"))}record_of(&old,who,text)?;journal::append_locked(&l,json!({"t":"session/message","round":i,"session":sid,"role":role,"body":text}))?;Ok(())}
pub fn land_for(root:&Path,i:&str,body:&str,sid:&str)->Result<Value>{util::ident(sid)?;if body.is_empty()||body.len()>B||body.contains('\0'){return Err(Error::new("holder understanding invalid or oversized"))}let l=journal::Lock::take(root,"round")?;let rows=journal::read(root,"round")?;let versions=fold(&rows,i)?.1;if let Some(e)=rows.iter().find(|e|e.event["t"]=="holder/distill"&&e.event["round"]==i&&e.event["session"]==sid){if e.event["body"]!=body{return Err(Error::new("holder landing receipt mismatch"))}return version_at(&rows,i,e.seq,&versions)}if rows.iter().any(|e|e.event["t"]=="say/end"&&e.event["round"]==i&&e.event["session"]==sid){return Err(Error::new("session is already complete"))}let mut e=json!({"t":"holder/distill","round":i,"agent":"round","session":sid,"digest":h(body),"body":body});if let Some(last)=versions.as_array().and_then(|a|a.last()){e["against"]=last["digest"].clone()}journal::append_locked(&l,e)?;Ok(context(root,i)?["version"].clone())}

pub fn finish(root:&Path,i:&str,body:&str,sid:&str)->Result<Value>{ck(i)?;util::ident(sid)?;if body.is_empty()||body.len()>1024*1024||body.contains('\0'){return Err(Error::new("holder reply exceeds archive bounds; completed response preserved for review"))}let l=journal::Lock::take(root,"round")?;let rows=journal::read(root,"round")?;let(archive,versions)=fold(&rows,i)?;let prior=rows.iter().find(|e|e.event["t"]=="holder/distill"&&e.event["round"]==i&&e.event["session"]==sid);if prior.is_some_and(|e|e.event["body"]!=body){return Err(Error::new("holder landing receipt mismatch"))}let archived=rows.iter().find(|e|e.event["t"]=="session/message"&&e.event["round"]==i&&e.event["session"]==sid&&e.event["role"]=="assistant");if archived.is_some_and(|e|e.event["body"]!=body){return Err(Error::new("holder archival receipt mismatch"))}if archived.is_some_and(|a|prior.is_none_or(|p|p.seq>=a.seq)){return Err(Error::new("holder archive has no preceding landing receipt"))}let ended=rows.iter().any(|e|e.event["t"]=="say/end"&&e.event["round"]==i&&e.event["session"]==sid);if ended&&(prior.is_none()||archived.is_none()){return Err(Error::new("completed session lacks its preceding landing/archive receipts"))}let digest=h(body);let mut es=vec![];if prior.is_none(){let mut e=json!({"t":"holder/distill","round":i,"agent":"round","session":sid,"digest":digest,"body":body});if let Some(v)=versions.as_array().and_then(|a|a.last()){e["against"]=v["digest"].clone()}es.push(e)}if archived.is_none(){record_of(&archive,"持轮者",body)?;es.push(json!({"t":"session/message","round":i,"session":sid,"role":"assistant","body":body}))}if !rows.iter().any(|e|e.event["t"]=="say/end"&&e.event["round"]==i&&e.event["session"]==sid){es.push(json!({"t":"say/end","round":i,"session":sid}))}if !es.is_empty(){journal::preflight_locked(&l,&es)?;journal::append_many_locked(&l,es)?;}let rows=journal::read(root,"round")?;let versions=fold(&rows,i)?.1;let seq=rows.iter().find(|e|e.event["t"]=="holder/distill"&&e.event["round"]==i&&e.event["session"]==sid).map(|e|e.seq).ok_or_else(||Error::new("holder finish landing receipt missing"))?;version_at(&rows,i,seq,&versions)}

fn version_at(rows:&[journal::Row],i:&str,seq:u64,versions:&Value)->Result<Value>{let n=rows.iter().filter(|r|r.seq<=seq&&r.event["t"]=="holder/distill"&&r.event["round"]==i).count();versions.as_array().and_then(|a|n.checked_sub(1).and_then(|n|a.get(n))).cloned().ok_or_else(||Error::new("holder landing projection missing"))}
