use crate::{Error,Result,git::{self,Git,Entry},journal,util};
use serde_json::{Value,json};
use std::{collections::{BTreeMap,BTreeSet},path::{Path,PathBuf}};
fn e(x:impl std::fmt::Display)->Error{Error::new(x.to_string())}
fn p(raw:&str,r:bool)->Result<String>{let mut s=raw.trim();while let Some(x)=s.strip_prefix("./"){s=x}while s.len()>1&&s.ends_with('/'){s=&s[..s.len()-1]}if s.is_empty()||s=="."{if r{return Ok(String::new())}return Err(e("a file path is required"))}util::rel(s)?;Ok(s.into())}
fn under(a:&str,b:&str)->bool{b.is_empty()&&!a.is_empty()||a.starts_with(&format!("{b}/"))}
fn ancestors(p:&str)->impl Iterator<Item=&str>{p.match_indices('/').map(|(i,_)|&p[..i])}
fn text<'a>(v:&'a Value,k:&str)->Result<&'a str>{v.get(k).and_then(Value::as_str).ok_or_else(||e(format!("view event requires string {k}")))}
fn num(v:&Value,k:&str)->Result<u64>{v.get(k).and_then(|x|x.as_u64().or_else(||x.as_f64().filter(|x|x.is_finite()&&*x>=0.0&&*x<=9007199254740991.0&&x.fract()==0.0).map(|x|x as u64))).filter(|x|*x<=9007199254740991).ok_or_else(||e(format!("view event requires safe integer {k}")))}
fn mode(v:&Value)->Result<u32>{let m=u32::try_from(num(v,"mode")?).map_err(e)?;if !matches!(m,0o100644|0o100755){return Err(e("view event file mode must be canonical 100644 or 100755"))}Ok(m)}
fn norm(m:u32)->u32{if m&0o111!=0{0o100755}else{0o100644}}
pub fn ref_for(w:&str)->Result<String>{util::ident(w)?;Ok(if w=="round"{"refs/heads/main".into()}else{format!("refs/heads/{w}")})}
#[derive(Clone,Debug)]pub struct View{pub root:PathBuf,pub writer:String,pub base:Option<String>,pub rev:u64,pub revs:Vec<u64>,pub entries:BTreeMap<String,Entry>,g:Git,l:BTreeMap<String,Entry>,u:BTreeMap<String,Option<Entry>>,h:Vec<(u64,Value)>}
impl View{
 pub fn load(root:&Path,w:&str,to:Option<u64>)->Result<Self>{util::ident(w)?;if to.is_some_and(|x|x>9007199254740991){return Err(e("revision exceeds safe integer range"))}let g=Git::open(root)?;let base=g.resolve(&ref_for(w)?)?;let l=match &base{Some(x)=>g.tree_all(x)?,None=>BTreeMap::new()};let entries=l.iter().filter(|(_,v)|v.kind!="dir").map(|(k,v)|(k.clone(),v.clone())).collect();let mut v=Self{root:g.root.clone(),writer:w.into(),base,rev:0,revs:vec![0],entries,g,l,u:BTreeMap::new(),h:vec![]};for r in journal::read(&v.root,w)?{let t=text(&r.event,"t")?;if t.starts_with("view/")||t=="ckpt/commit"{let n=num(&r.event,"rev")?;if to.is_some_and(|x|n>x){continue}v.replay(&r.event)?;}}Ok(v)}
 fn a(&self,p:&str)->Option<Entry>{if let Some(Some(v))=self.u.get(p){return Some(v.clone())}if self.u.iter().any(|(k,v)|v.is_some()&&under(k,p)){return Some(Entry{kind:"dir".into(),mode:0o40000,id:self.empty()})}if self.u.contains_key(p)||ancestors(p).any(|x|self.u.contains_key(x)){return None}self.l.get(p).cloned()}
 fn empty(&self)->String{if self.base.as_ref().is_some_and(|x|x.len()==64){"6ef19b41225c5369f1c104d45d8d85efa9b057b53b14b4b9b939dd74decc5321".into()}else{"4b825dc642cb6eb9a060e54bf8d69288fbee4904".into()}}
 fn rebuild(&mut self)->Result<()>{let mut m=BTreeMap::new();for(k,v)in &self.l{if v.kind=="dir"||self.u.contains_key(k)||ancestors(k).any(|x|self.u.get(x)==Some(&None)||self.u.get(x).is_some_and(Option::is_some)){continue}m.insert(k.clone(),v.clone());}for(k,v)in &self.u{if let Some(v)=v{m.insert(k.clone(),v.clone());}}Self::valid(&m)?;self.entries=m;Ok(())}
 fn valid(m:&BTreeMap<String,Entry>)->Result<()>{if m.len()>util::MAX_EVENTS{return Err(e("view has too many entries"))}for(k,v)in m{util::rel(k)?;if git::kind(v.mode)?!=v.kind||v.kind=="dir"{return Err(e("invalid view leaf entry"))}git::oid(&v.id)?;if ancestors(k).any(|a|m.contains_key(a)){return Err(e("view leaf blocks a descendant"))}}Ok(())}
 pub fn read(&self,path:&str)->Result<Option<Vec<u8>>>{let path=p(path,false)?;match self.a(&path){Some(v)if v.kind=="file"||v.kind=="symlink"=>self.g.blob(&v.id).map(Some),_=>Ok(None)}}
 fn meta(&self,v:&Entry)->Result<Value>{let n=if v.kind=="file"||v.kind=="symlink"{self.g.blob_size(&v.id)?}else{0};Ok(json!({"kind":v.kind,"mode":v.mode,"size":n,"id":v.id}))}
 pub fn stat(&self,path:&str)->Result<Value>{let path=p(path,false)?;match self.a(&path){Some(v)=>self.meta(&v),None=>Ok(Value::Null)}}
 pub fn list(&self,path:&str)->Result<Value>{let d=p(path,true)?;if !d.is_empty()&&self.a(&d).is_none_or(|x|x.kind!="dir"){return Ok(json!([]))}let mut names=BTreeSet::new();for k in self.l.keys().chain(self.u.keys()){if under(k,&d){let rest=if d.is_empty(){k.as_str()}else{&k[d.len()+1..]};names.insert(rest.split('/').next().unwrap_or("").to_owned());}}let mut names=names.into_iter().collect::<Vec<_>>();names.sort_by(|a,b|a.encode_utf16().cmp(b.encode_utf16()));let rows=names.into_iter().filter_map(|n|{let q=if d.is_empty(){n.clone()}else{format!("{d}/{n}")};self.a(&q).map(|v|(n,v))}).collect::<Vec<_>>();let ids=rows.iter().filter(|(_,v)|v.kind=="file"||v.kind=="symlink").map(|(_,v)|v.id.as_str()).collect::<Vec<_>>();let mut sizes=self.g.blob_sizes(&ids)?.into_iter();let mut out=Vec::new();for(n,v)in rows{let size=if v.kind=="file"||v.kind=="symlink"{sizes.next().ok_or_else(||e("missing list metadata"))?}else{0};out.push(json!({"name":n,"kind":v.kind,"mode":v.mode,"size":size,"id":v.id}));}Ok(out.into())}
 pub fn diff(&self,since:u64)->Result<Value>{if since>9007199254740991{return Err(e("revision exceeds safe range"))}Ok(self.h.iter().filter(|(n,_)|*n>since).map(|(_,v)|v.clone()).collect::<Vec<_>>().into())}
 fn check_write(&self,k:&str)->Result<()>{if self.a(k).is_some_and(|v|v.kind=="dir"||v.kind=="gitlink"){return Err(e("cannot overwrite a directory or gitlink"))}for a in ancestors(k){if self.a(a).is_some_and(|v|v.kind!="dir"){return Err(e(format!("ancestor {a} is not a directory")))}}Ok(())}
 fn replay(&mut self,v:&Value)->Result<()>{let t=text(v,"t")?;if text(v,"agent")?!=self.writer{return Err(e("view event agent does not match writer"))}let n=num(v,"rev")?;if t=="ckpt/commit"{if n!=self.rev{return Err(e("checkpoint revision does not match view history"))}let c=text(v,"commit")?;git::oid(c)?;let _=text(v,"msg")?;if self.g.resolve(c)?.as_deref()!=Some(c){return Err(e("checkpoint commit does not exist"))}if !self.revs.contains(&n){self.revs.push(n)}return Ok(())}if n!=self.rev.checked_add(1).ok_or_else(||e("view revision exhausted"))?{return Err(e("view revisions must be contiguous"))}let d=match t{
 "view/write"=>{let k=p(text(v,"path")?,false)?;let id=text(v,"blob")?;git::oid(id)?;let size=self.g.blob_size(id)?;if size>util::MAX_BYTES as u64{return Err(e("historic view blob exceeds byte budget"))}let m=mode(v)?;let kd=if self.u.get(&k).is_some_and(Option::is_some){"modify"}else{"add"};self.u.insert(k.clone(),Some(Entry{kind:"file".into(),mode:m,id:id.into()}));json!({"kind":kd,"path":k,"mode":m,"size":size})},
 "view/symlink"=>{let k=p(text(v,"path")?,false)?;let target=text(v,"target")?;if target.contains('\0')||target.len()>util::MAX_BYTES{return Err(e("invalid symlink target"))}let b=self.g.run(&["hash-object","--stdin"],Some(target.as_bytes()))?;let id:String=String::from_utf8(b).map_err(e)?.trim().into();let _=self.g.blob(&id)?;self.u.insert(k.clone(),Some(Entry{kind:"symlink".into(),mode:0o120000,id}));json!({"kind":"symlink","path":k,"target":target})},
 "view/remove"=>{let k=p(text(v,"path")?,false)?;self.u.retain(|x,_|!under(x,&k));self.u.insert(k.clone(),None);json!({"kind":"delete","path":k})},
 "view/rename"=>{let f=p(text(v,"from")?,false)?;let t=p(text(v,"to")?,false)?;if f==t||under(&t,&f){return Err(e("invalid rename topology"))}let q=self.u.get(&f).and_then(|x|x.clone()).ok_or_else(||e("rename source is not pinned in history"))?;self.u.retain(|x,_|!under(x,&f));self.u.insert(f.clone(),None);self.u.insert(t.clone(),Some(q));json!({"kind":"rename","from":f,"to":t})},
 "view/chmod"=>{let k=p(text(v,"path")?,false)?;let m=mode(v)?;let mut q=self.u.get(&k).and_then(|x|x.clone()).filter(|x|x.kind=="file").ok_or_else(||e("chmod source file is not pinned in history"))?;q.mode=m;self.u.insert(k.clone(),Some(q));json!({"kind":"chmod","path":k,"mode":m})},_=>return Err(e(format!("unknown view event type: {t}")))};self.rebuild()?;self.rev=n;self.revs.push(n);self.h.push((n,d));Ok(())}
 fn guard(&self)->Result<journal::Lock>{let l=journal::Lock::take(&self.root,&self.writer)?;let q=Self::load(&self.root,&self.writer,None)?;if self.base!=q.base||self.rev!=q.rev||self.entries!=q.entries||self.u!=q.u||self.h!=q.h{return Err(e("view is stale; reload before writing"))}Ok(l)}
 fn event(&self,t:&str)->Value{json!({"t":t,"agent":self.writer,"rev":self.rev+1})}
 fn publish(&mut self,l:&journal::Lock,v:Vec<Value>)->Result<u64>{if v.is_empty(){return Ok(self.rev)}let mut q=self.clone();for e in &v{q.replay(e)?;}journal::append_many_locked(l,v)?;*self=q;Ok(self.rev)}
 pub fn write(&mut self,path:&str,b:&[u8],mode:Option<u32>)->Result<u64>{let k=p(path,false)?;self.check_write(&k)?;if b.len()>util::MAX_BYTES{return Err(e("write exceeds byte limit"))}let l=self.guard()?;let id=self.g.put_blob(b)?;let mut v=self.event("view/write");v["path"]=k.into();v["blob"]=id.into();v["mode"]=norm(mode.unwrap_or(0o100644)).into();self.publish(&l,vec![v])}
 pub fn symlink(&mut self,path:&str,target:&str)->Result<u64>{let k=p(path,false)?;self.check_write(&k)?;if target.contains('\0')||target.len()>util::MAX_BYTES{return Err(e("invalid symlink target"))}let l=self.guard()?;self.g.put_blob(target.as_bytes())?;let mut v=self.event("view/symlink");v["path"]=k.into();v["target"]=target.into();self.publish(&l,vec![v])}
 pub fn remove(&mut self,path:&str)->Result<u64>{let k=p(path,false)?;if self.a(&k).is_none(){return Err(e("remove path does not exist"))}let l=self.guard()?;let mut v=self.event("view/remove");v["path"]=k.into();self.publish(&l,vec![v])}
 fn pin(&self,k:&str,n:u64)->Result<Option<Value>>{if self.u.get(k).is_some_and(Option::is_some){return Ok(None)}let q=self.a(k).ok_or_else(||e("pin source does not exist"))?;Ok(Some(if q.kind=="file"{json!({"t":"view/write","agent":self.writer,"rev":n,"path":k,"blob":q.id,"mode":q.mode})}else if q.kind=="symlink"{let b=self.g.blob(&q.id)?;let t=String::from_utf8(b).map_err(|_|e("non-UTF-8 symlink target"))?;json!({"t":"view/symlink","agent":self.writer,"rev":n,"path":k,"target":t})}else{return Err(e("only files and symlinks may be pinned"))}))}
 pub fn rename(&mut self,from:&str,to:&str)->Result<u64>{let f=p(from,false)?;let t=p(to,false)?;if f==t||under(&t,&f){return Err(e("invalid rename topology"))}let q=self.a(&f).ok_or_else(||e("rename source does not exist"))?;if !matches!(q.kind.as_str(),"file"|"symlink"){return Err(e("directory/gitlink rename is unsupported"))}if self.a(&t).is_some(){return Err(e("rename target already exists"))}self.check_write(&t)?;let l=self.guard()?;let mut v=Vec::new();if let Some(x)=self.pin(&f,self.rev+1)?{v.push(x)}v.push(json!({"t":"view/rename","agent":self.writer,"rev":self.rev+v.len() as u64+1,"from":f,"to":t}));self.publish(&l,v)}
 pub fn chmod(&mut self,path:&str,mode:u32)->Result<u64>{let k=p(path,false)?;let q=self.a(&k).filter(|x|x.kind=="file").ok_or_else(||e("chmod requires an existing file"))?;let m=norm(mode);let l=self.guard()?;if q.mode==m{return Ok(self.rev)}let mut v=Vec::new();if let Some(x)=self.pin(&k,self.rev+1)?{v.push(x)}v.push(json!({"t":"view/chmod","agent":self.writer,"rev":self.rev+v.len() as u64+1,"path":k,"mode":m}));self.publish(&l,v)}
 /// Validate all outputs before emitting upstream-compatible individual events.
 /// A crash may preserve a complete event prefix, as with the upstream journal.
 pub fn apply_batch(&mut self,changes:&BTreeMap<String,Option<Entry>>)->Result<u64>{if changes.is_empty(){return Ok(self.rev)}let l=self.guard()?;let mut q=self.clone();let mut v=Vec::new();for(k,_)in changes.iter().filter(|(_,x)|x.is_none()){let k=p(k,false)?;if q.a(&k).is_none(){continue}let mut z=q.event("view/remove");z["path"]=k.into();q.replay(&z)?;v.push(z)}for(k,x)in changes.iter().filter(|(_,x)|x.is_some()){let k=p(k,false)?;let x=x.as_ref().ok_or_else(||e("missing batch entry"))?;if q.entries.get(&k)==Some(x){continue}q.check_write(&k)?;git::oid(&x.id)?;if git::kind(x.mode)?!=x.kind||!matches!(x.kind.as_str(),"file"|"symlink"){return Err(e("batch output requires file or symlink"))}let b=q.g.blob(&x.id)?;let mut z=q.event(if x.kind=="file"{"view/write"}else{"view/symlink"});z["path"]=k.into();if x.kind=="file"{z["blob"]=x.id.clone().into();z["mode"]=x.mode.into();}else{z["target"]=String::from_utf8(b).map_err(|_|e("non-UTF-8 symlink target"))?.into()}q.replay(&z)?;v.push(z)}self.publish(&l,v)}
 pub fn checkpoint(&mut self,msg:&str)->Result<Value>{if msg.contains('\0')||msg.len()>util::MAX_BYTES{return Err(e("invalid checkpoint message"))}let l=self.guard()?;let tree=self.g.put_tree(&self.entries)?;let parents=self.base.iter().cloned().collect::<Vec<_>>();let commit=self.g.commit_tree(&tree,&parents,msg)?;let rf=ref_for(&self.writer)?;let v=json!({"t":"ckpt/commit","agent":self.writer,"commit":commit,"rev":self.rev,"msg":msg});journal::preflight_locked(&l,std::slice::from_ref(&v))?;self.g.advance(&rf,&commit,self.base.as_deref())?;let seq=journal::append_locked(&l,v).map_err(|x|e(format!("checkpoint ref advanced to {commit}, but journal durability failed: {x}; inspect and reload")))?;self.base=Some(commit.clone());self.l=self.g.tree_all(&commit)?;self.rebuild()?;Ok(json!({"commit":commit,"ref":rf,"tree":tree,"parents":parents,"entries":self.entries.len(),"seq":seq}))}
}
pub fn branch(root:&Path,w:&str,base:&str)->Result<Value>{let rf=ref_for(w)?;let g=Git::open(root)?;let base=g.resolve(base)?.ok_or_else(||e("branch base does not exist"))?;if let Some(q)=g.resolve(&rf)?{if q==base{return Ok(json!({"ref":rf,"base":base,"moved":false}))}return Err(e(format!("branch {rf} already points to {q}; choose that base or explicitly move the ref")))}match g.advance(&rf,&base,None){Ok(())=>Ok(json!({"ref":rf,"base":base,"moved":true})),Err(x)=>{if g.resolve(&rf)?.as_deref()==Some(&base){Ok(json!({"ref":rf,"base":base,"moved":false}))}else{Err(x)}}}}
