//! Black-box CLI and approval gates. No provider calls are allowed here.
use std::{path::Path,process::{Command,Output,Stdio},io::Write};
use serde_json::{Value,json};use fugue::{git::Git,journal};
fn call(r:&Path,args:&[&str],input:Option<&[u8]>)->Output{let mut c=Command::new(env!("CARGO_BIN_EXE_fugue"));c.arg("--root").arg(r).env("FUGUE_SYSTEM_DIR",r.join("missing-system")).args(args).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped());let mut p=c.spawn().unwrap();if let Some(b)=input{p.stdin.take().unwrap().write_all(b).unwrap()}else{drop(p.stdin.take())}p.wait_with_output().unwrap()}
fn j(r:&Path,args:&[&str])->Value{let mut a=vec!["--json"];a.extend(args);let q=call(r,&a,None);assert!(q.status.success(),"{}",String::from_utf8_lossy(&q.stderr));serde_json::from_slice(&q.stdout).unwrap()}
fn repo()->(tempfile::TempDir,String){let d=tempfile::tempdir().unwrap();assert!(Command::new("git").args(["init","-q","-b","main"]).arg(d.path()).status().unwrap().success());let g=Git::open(d.path()).unwrap();let t=g.put_tree(&Default::default()).unwrap();let b=g.commit_tree(&t,&[],"base").unwrap();g.advance("refs/heads/main",&b,None).unwrap();(d,b)}
#[test]fn help_and_unknown_flags_have_distinct_exit_codes(){let d=tempfile::tempdir().unwrap();assert!(call(d.path(),&["--help"],None).status.success());for a in [&["--json","read","a","--typo"][..],&["--json","unknown"][..],&["--json","watch","--interval","0"][..],&["--json","round","plan","goal","--live","--wire-in","x"][..]]{let q=call(d.path(),a,None);assert_eq!(q.status.code(),Some(2));let v:Value=serde_json::from_slice(&q.stderr).unwrap();assert_eq!(v["code"],2);}assert!(!d.path().join(".fugue").exists());}
#[test]fn binary_virtual_writes_never_change_host_or_index(){let(d,_)=repo();let q=call(d.path(),&["--json","write","nested/file","--stdin"],Some(b"a\0b\n"));assert!(q.status.success());assert_eq!(j(d.path(),&["stat","nested/file"])["size"],4);assert_eq!(call(d.path(),&["read","nested/file"],None).stdout,b"a\0b\n");assert!(!d.path().join("nested").exists());assert!(!d.path().join(".git/index").exists());j(d.path(),&["rename","nested/file","nested/new"]);j(d.path(),&["chmod","nested/new","755"]);assert_eq!(j(d.path(),&["revs"]),json!([0,1,2,3]));let c=j(d.path(),&["commit","-m","checkpoint"]);assert!(c["commit"].as_str().is_some());assert!(!d.path().join("nested/new").exists());j(d.path(),&["replay","--verify"]);}
#[test]fn readonly_observation_creates_no_fugue_storage(){let(d,_)=repo();for a in [&["--json","status","--once"][..],&["--json","log"][..],&["watch"][..],&["tui","--once"][..],&["--json","config","show"][..]]{assert!(call(d.path(),a,None).status.success())}assert!(!d.path().join(".fugue").exists());}
#[test]fn plan_gate_approves_once_and_keeps_pinned_base(){let(d,b)=repo();j(d.path(),&["config","set","actions.ok",r#"{"argv":["/usr/bin/true"]}"#]);j(d.path(),&["config","set","round.split",r#"[{"goal":"g","ownedPaths":["a"],"assertions":[{"name":"n","action":"ok"}]}]"#]);let p=j(d.path(),&["round","plan","goal"]);assert_eq!(p["state"],"Planning");assert_eq!(Git::open(d.path()).unwrap().resolve("refs/heads/main").unwrap(),Some(b.clone()));assert!(journal::read(d.path(),"round").unwrap().iter().all(|e|e.event["t"]!="contract/issue"));let q=j(d.path(),&["round","go"]);assert_eq!(q["base"],b);let before=journal::read(d.path(),"round").unwrap();let q=call(d.path(),&["--json","round","go"],None);assert_eq!(q.status.code(),Some(1));assert_eq!(journal::read(d.path(),"round").unwrap(),before);assert!(!d.path().join("a").exists());}
#[test]fn path_escapes_and_bad_config_are_explicit(){let(d,_)=repo();for p in ["../escape",".git/config","a/.fugue/config"]{let q=call(d.path(),&["--json","write",p,"--stdin"],Some(b"oops"));assert!(!q.status.success());assert!(q.stdout.is_empty());}assert!(journal::merged(d.path()).unwrap().is_empty());let q=call(d.path(),&["--json","config","set","round.id",r#"{"x":1,"x":2}"#],None);assert!(!q.status.success());assert!(!d.path().join(".fugue/config").exists());}
#[test]fn assemble_requires_named_protocol_and_offline_say_does_not_call_model(){let(d,_)=repo();assert_eq!(call(d.path(),&["--json","assemble"],None).status.code(),Some(2));let q=j(d.path(),&["assemble","holder"]);assert_eq!(q["protocol"],"holder");let q=j(d.path(),&["say","remember this"]);assert_eq!(q["recorded"],true);assert_eq!(q["modelUsed"],false);assert!(journal::read(d.path(),"round").unwrap().iter().all(|e|e.event["t"]!="llm/call"));}
#[test]fn full_tui_non_tty_snapshot_is_read_only_without_terminal_escapes(){let d=tempfile::tempdir().unwrap();let q=call(d.path(),&["tui","--full"],None);assert_eq!(q.status.code(),Some(0));assert!(!q.stdout.contains(&0x1b));assert!(!d.path().join(".fugue").exists());}

#[test]fn unexpected_positionals_fail_before_any_storage_or_mutation(){let(d,_)=repo();for a in [&["--json","config","show","unused"][..],&["--json","write","a","extra","--stdin"][..],&["--json","status","extra"][..],&["--json","doctor","extra"][..],&["--json","fork","main","extra"][..]]{let q=call(d.path(),a,Some(b"bad"));assert_eq!(q.status.code(),Some(2),"{a:?}");}assert!(!d.path().join(".fugue").exists());assert!(!d.path().join(".git/index").exists());}

#[test]fn compiled_version_is_workspace_independent_and_routing_missing_values_fail_closed(){let d=tempfile::tempdir().unwrap();let bin=env!("CARGO_BIN_EXE_fugue");let missing=d.path().join("not-created");let q=Command::new(bin).args(["--version","--json","--root"]).arg(&missing).current_dir(d.path()).output().unwrap();assert!(q.status.success());assert_eq!(serde_json::from_slice::<Value>(&q.stdout).unwrap(),json!({"name":"fugue","version":env!("CARGO_PKG_VERSION")}));assert!(!missing.exists());for a in [&["--version","status"][..],&["--version=1"][..],&["--version","--agent","x"][..],&["status","--root="][..],&["status","--agent="][..],&["write","a","--stdin","--agent"][..]]{let q=Command::new(bin).args(a).current_dir(d.path()).output().unwrap();assert_eq!(q.status.code(),Some(2),"{a:?}");assert!(q.stdout.is_empty());}for flag in ["--root","--agent"]{let q=Command::new(bin).args(["--help",flag]).current_dir(d.path()).output().unwrap();assert!(q.status.success());assert!(String::from_utf8(q.stdout).unwrap().contains("--version"));}assert!(std::fs::read_dir(d.path()).unwrap().next().is_none());}
