use fugue::{git::{Git,Entry},journal::{self,Lock},view::{View,branch},util};
use serde_json::{Value,json};
use std::{collections::BTreeMap,fs,io::Write,process::Command};
fn repo()->tempfile::TempDir{let d=tempfile::tempdir().unwrap();assert!(Command::new("git").args(["init","-q","--initial-branch=main"]).arg(d.path()).status().unwrap().success());d}
fn entry(g:&Git,bytes:&[u8],mode:u32)->Entry{Entry{kind:"file".into(),mode,id:g.put_blob(bytes).unwrap()}}
fn envelope(seq:u64,w:&str,event:Value)->Vec<u8>{let mut v=event;v["seq"]=seq.into();v["writer"]=w.into();let crc=format!("{:08x}",crc32fast::hash(util::canonical(&v).unwrap().as_bytes()));v["crc"]=crc.into();let mut b=serde_json::to_vec(&v).unwrap();b.push(b'\n');b}
#[test]fn git_binary_tree_modes_cas_and_no_worktree_writes(){let d=repo();let g=Git::open(d.path()).unwrap();fs::write(d.path().join("host"),b"untouched").unwrap();let before=fs::read(d.path().join(".git/HEAD")).unwrap();let mut m=BTreeMap::new();m.insert("tab\tnewline\n".into(),entry(&g,b"a\0b\xff",0o100644));m.insert("sub/x".into(),entry(&g,b"executable",0o100755));let t=g.put_tree(&m).unwrap();let c=g.commit_tree(&t,&[],"multiple\nlines\n").unwrap();assert_eq!(g.tree(&c).unwrap(),m);assert_eq!(g.blob(&m["tab\tnewline\n"].id).unwrap(),b"a\0b\xff");g.advance("refs/heads/main",&c,None).unwrap();assert!(g.advance("refs/heads/main",&c,None).unwrap_err().message.contains("CAS"));assert_eq!(g.resolve("main").unwrap(),Some(c));assert!(g.resolve(&t).is_err());assert!(g.run(&["checkout","main"],None).is_err());assert_eq!(fs::read(d.path().join("host")).unwrap(),b"untouched");assert_eq!(fs::read(d.path().join(".git/HEAD")).unwrap(),before);assert!(!d.path().join(".git/index").exists());}
#[test]fn git_rejects_injection_tree_conflicts_and_bad_modes(){let d=repo();let g=Git::open(d.path()).unwrap();assert!(g.resolve("--help").is_err());assert!(g.blob("HEAD").is_err());let mut m=BTreeMap::new();m.insert("a".into(),entry(&g,b"x",0o100644));m.insert("a/b".into(),entry(&g,b"x",0o100644));assert!(g.put_tree(&m).is_err());m.clear();m.insert("../escape".into(),entry(&g,b"x",0o100644));assert!(g.put_tree(&m).is_err());m.clear();m.insert("x".into(),entry(&g,b"x",0o100600));assert!(g.put_tree(&m).is_err());assert!(g.advance("HEAD",&"1".repeat(40),None).is_err());}
#[test]fn git_sha256_roundtrip(){let d=tempfile::tempdir().unwrap();let out=Command::new("git").args(["init","-q","--object-format=sha256","--initial-branch=main"]).arg(d.path()).output().unwrap();if !out.status.success(){return}let g=Git::open(d.path()).unwrap();let mut m=BTreeMap::new();m.insert("x".into(),entry(&g,b"sha256",0o100644));let t=g.put_tree(&m).unwrap();assert_eq!(t.len(),64);let c=g.commit_tree(&t,&[],"root").unwrap();g.advance("refs/heads/main",&c,None).unwrap();assert_eq!(g.tree(&c).unwrap(),m);let mut v=View::load(d.path(),"round",None).unwrap();v.symlink("sub/link","../x").unwrap();assert_eq!(v.stat("sub").unwrap()["id"].as_str().unwrap().len(),64);v.checkpoint("links").unwrap();assert_eq!(View::load(d.path(),"round",None).unwrap().read("sub/link").unwrap().unwrap(),b"../x");}
#[test]fn journal_reads_are_observational_and_merge_is_deterministic(){let d=tempfile::tempdir().unwrap();assert!(journal::read(d.path(),"round").unwrap().is_empty());assert!(journal::merged(d.path()).unwrap().is_empty());assert!(!d.path().join(".fugue").exists());journal::append(d.path(),"agent/r1/1",json!({"t":"signal","value":"α"})).unwrap();journal::append(d.path(),"round",json!({"t":"signal","n":1})).unwrap();journal::append(d.path(),"agent/r1/1",json!({"t":"signal","n":2})).unwrap();let v=journal::merged(d.path()).unwrap();assert_eq!(v.iter().map(|x|(x.seq,x.writer.as_str())).collect::<Vec<_>>(),vec![(1,"agent/r1/1"),(1,"round"),(2,"agent/r1/1")]);assert_eq!(journal::read(d.path(),"agent/r1/1").unwrap()[0].event["value"],"α");}
#[test]fn journal_crc_seq_duplicates_and_complete_corruption_fail_closed(){let d=tempfile::tempdir().unwrap();journal::append(d.path(),"round",json!({"t":"signal","v":1})).unwrap();let p=d.path().join(".fugue/log/round.jsonl");let good=fs::read(&p).unwrap();let mut v:Value=serde_json::from_slice(&good).unwrap();v["v"]=2.into();fs::write(&p,format!("{}\n",v)).unwrap();let bad=fs::read(&p).unwrap();assert!(journal::read(d.path(),"round").is_err());assert!(journal::append(d.path(),"round",json!({"t":"signal"})).is_err());assert_eq!(fs::read(&p).unwrap(),bad);fs::write(&p,envelope(2,"round",json!({"t":"signal"}))).unwrap();assert!(journal::read(d.path(),"round").is_err());fs::write(&p,[good.clone(),good.clone()].concat()).unwrap();assert!(journal::read(d.path(),"round").is_err());let s=String::from_utf8(good.clone()).unwrap().replace("\"seq\":1","\"seq\":1,\"seq\":1");fs::write(&p,s).unwrap();assert!(journal::read(d.path(),"round").is_err());fs::write(&p,envelope(1,"other",json!({"t":"signal"}))).unwrap();assert!(journal::read(d.path(),"round").is_err());fs::write(&p,&good).unwrap();let before=fs::read(&p).unwrap();assert!(journal::append(d.path(),"round",json!({"t":"signal","writer":"other"})).is_err());assert_eq!(fs::read(&p).unwrap(),before);}
#[test]fn journal_partial_tail_is_ignored_on_read_and_repaired_before_append(){let d=tempfile::tempdir().unwrap();journal::append(d.path(),"round",json!({"t":"signal","n":1})).unwrap();let p=d.path().join(".fugue/log/round.jsonl");let mut f=fs::OpenOptions::new().append(true).open(&p).unwrap();f.write_all(b"{\"seq\":2,\"truncated\":\xff").unwrap();let b=fs::read(&p).unwrap();assert_eq!(journal::read(d.path(),"round").unwrap().len(),1);assert_eq!(fs::read(&p).unwrap(),b);assert_eq!(journal::append(d.path(),"round",json!({"t":"signal","n":2})).unwrap(),2);assert_eq!(journal::read(d.path(),"round").unwrap().len(),2);assert!(!fs::read(&p).unwrap().contains(&0xff));}
#[test]fn journal_lock_same_writer_exclusion_stale_recovery_and_batch(){let d=tempfile::tempdir().unwrap();let l=Lock::take(d.path(),"round").unwrap();assert!(Lock::take(d.path(),"round").is_err());let other=Lock::take(d.path(),"agent/r/1").unwrap();journal::append_locked(&other,json!({"t":"signal"})).unwrap();assert_eq!(journal::append_many_locked(&l,vec![json!({"t":"signal","n":1}),json!({"t":"signal","n":2})]).unwrap(),2);drop(l);let p=d.path().join(".fugue/log/round.lock");fs::write(&p,json!({"v":1,"writer":"round","pid":9999999,"start":0,"boot":"definitely-an-old-boot"}).to_string()).unwrap();let l=Lock::take(d.path(),"round").unwrap();drop(l);assert!(!p.exists());fs::write(&p,b"garbage").unwrap();assert!(Lock::take(d.path(),"round").is_err());assert_eq!(fs::read(&p).unwrap(),b"garbage");}
#[test]fn journal_rejects_symlinks_hardlinks_and_fifo_without_touching_target(){use std::os::unix::fs::symlink;let d=tempfile::tempdir().unwrap();let outside=tempfile::tempdir().unwrap();symlink(outside.path(),d.path().join(".fugue")).unwrap();assert!(journal::append(d.path(),"round",json!({"t":"signal"})).is_err());assert_eq!(fs::read_dir(outside.path()).unwrap().count(),0);fs::remove_file(d.path().join(".fugue")).unwrap();fs::create_dir_all(d.path().join(".fugue/log")).unwrap();let target=outside.path().join("target");fs::write(&target,b"protected").unwrap();let p=d.path().join(".fugue/log/round.jsonl");symlink(&target,&p).unwrap();assert!(journal::read(d.path(),"round").is_err());assert!(journal::append(d.path(),"round",json!({"t":"signal"})).is_err());fs::remove_file(&p).unwrap();fs::hard_link(&target,&p).unwrap();assert!(journal::append(d.path(),"round",json!({"t":"signal"})).is_err());assert_eq!(fs::read(&target).unwrap(),b"protected");fs::remove_file(&p).unwrap();let p0=std::ffi::CString::new(p.to_str().unwrap()).unwrap();assert_eq!(unsafe{libc::mkfifo(p0.as_ptr(),0o600)},0);assert!(journal::read(d.path(),"round").is_err());assert!(journal::append(d.path(),"round",json!({"t":"signal"})).is_err());}
#[test]fn view_overlay_tombstone_recreation_and_historical_revisions(){let d=repo();let mut v=View::load(d.path(),"round",None).unwrap();assert_eq!(v.write("d/a",b"a",None).unwrap(),1);v.write("d/b",b"b",None).unwrap();v.checkpoint("first").unwrap();v.remove("d").unwrap();v.write("d/new",b"new",None).unwrap();assert!(v.read("d/a").unwrap().is_none());assert_eq!(v.list("d").unwrap().as_array().unwrap().len(),1);let q=View::load(d.path(),"round",None).unwrap();assert_eq!(q.entries,v.entries);assert_eq!(q.diff(0).unwrap(),v.diff(0).unwrap());assert_eq!(q.revs,vec![0,1,2,3,4]);let old=View::load(d.path(),"round",Some(2)).unwrap();assert_eq!(old.read("d/a").unwrap().unwrap(),b"a");assert!(old.read("d/new").unwrap().is_none());assert_eq!(v.diff(2).unwrap(),json!([{"kind":"delete","path":"d"},{"kind":"add","path":"d/new","mode":0o100644,"size":3}]));}
#[test]fn view_rename_and_chmod_pin_lower_bytes_across_checkpoint_and_noop(){let d=repo();let g=Git::open(d.path()).unwrap();let mut m=BTreeMap::new();m.insert("source".into(),entry(&g,b"pinned",0o100644));m.insert("other".into(),entry(&g,b"other",0o100644));let t=g.put_tree(&m).unwrap();let c=g.commit_tree(&t,&[],"initial").unwrap();g.advance("refs/heads/main",&c,None).unwrap();let mut v=View::load(d.path(),"round",None).unwrap();assert_eq!(v.chmod("source",0o600).unwrap(),0);assert!(journal::read(d.path(),"round").unwrap().is_empty());assert_eq!(v.rename("source","renamed").unwrap(),2);assert_eq!(v.chmod("other",0o700).unwrap(),4);v.checkpoint("pin").unwrap();let q=View::load(d.path(),"round",None).unwrap();assert_eq!(q.entries,v.entries);assert_eq!(q.diff(0).unwrap(),v.diff(0).unwrap());assert!(q.read("source").unwrap().is_none());assert_eq!(q.read("renamed").unwrap().unwrap(),b"pinned");assert_eq!(q.stat("other").unwrap()["mode"],0o100755);}
#[test]fn view_validates_before_journal_and_rejects_stale_snapshots(){let d=repo();let mut a=View::load(d.path(),"round",None).unwrap();let mut b=a.clone();assert!(a.remove("missing").is_err());assert!(!d.path().join(".fugue").exists());a.write("file",b"safe",None).unwrap();assert!(b.write("race",b"bad",None).is_err());assert!(a.write("file/child",b"bad",None).is_err());assert!(a.rename("file","file").is_err());assert!(a.write("../outside",b"bad",None).is_err());assert_eq!(journal::read(d.path(),"round").unwrap().len(),1);journal::append(d.path(),"round",json!({"t":"run/end","agent":"round","exit":0})).unwrap();assert_eq!(a.write("okay",b"a",None).unwrap(),2);}
#[test]fn view_batch_prevalidates_all_and_ref_branches_are_idempotent(){let d=repo();let g=Git::open(d.path()).unwrap();let mut v=View::load(d.path(),"round",None).unwrap();v.write("old",b"old",None).unwrap();let mut m=BTreeMap::new();m.insert("old".into(),None);m.insert("new".into(),Some(entry(&g,b"new",0o100644)));m.insert("new/child".into(),Some(entry(&g,b"bad",0o100644)));assert!(v.apply_batch(&m).is_err());assert_eq!(v.read("old").unwrap().unwrap(),b"old");assert_eq!(journal::read(d.path(),"round").unwrap().len(),1);m.remove("new/child");v.apply_batch(&m).unwrap();assert!(v.read("old").unwrap().is_none());assert_eq!(v.read("new").unwrap().unwrap(),b"new");let c=v.checkpoint("batch").unwrap()["commit"].as_str().unwrap().to_owned();assert_eq!(branch(d.path(),"agent/r1/1",&c).unwrap()["moved"],true);assert_eq!(branch(d.path(),"agent/r1/1",&c).unwrap()["moved"],false);assert!(journal::read(d.path(),"agent/r1/1").unwrap().is_empty());}
#[test]fn malformed_view_events_fail_without_mutation(){let d=repo();let g=Git::open(d.path()).unwrap();let id=g.put_blob(b"x").unwrap();journal::append(d.path(),"round",json!({"t":"view/write","agent":"round","path":"x","blob":id,"mode":0o100644,"rev":2})).unwrap();let p=d.path().join(".fugue/log/round.jsonl");let bytes=fs::read(&p).unwrap();assert!(View::load(d.path(),"round",None).is_err());assert_eq!(fs::read(p).unwrap(),bytes);}

#[test]fn journal_invalid_new_event_creates_no_storage(){let d=tempfile::tempdir().unwrap();assert!(journal::append(d.path(),"round",json!({"t":"signal","seq":1})).is_err());assert!(!d.path().join(".fugue").exists());}
#[test]fn git_merge_tree_real_disjoint_text_and_external_driver_refusal(){let d=repo();let g=Git::open(d.path()).unwrap();let mut m=BTreeMap::new();m.insert("text".into(),entry(&g,b"one\ntwo\nthree\n",0o100644));let t=g.put_tree(&m).unwrap();let base=g.commit_tree(&t,&[],"base").unwrap();m.insert("text".into(),entry(&g,b"ONE\ntwo\nthree\n",0o100644));let t=g.put_tree(&m).unwrap();let a=g.commit_tree(&t,&[base.clone()],"a").unwrap();m.insert("text".into(),entry(&g,b"one\ntwo\nTHREE\n",0o100644));let t=g.put_tree(&m).unwrap();let b=g.commit_tree(&t,&[base],"b").unwrap();let(z,out,err)=g.try_run(&["merge-tree","-z","--write-tree",&a,&b],None).unwrap();assert_eq!(z,0,"{}",String::from_utf8_lossy(&err));let id=std::str::from_utf8(out.split(|x|*x==0).next().unwrap()).unwrap();let m=g.tree(id).unwrap();assert_eq!(g.blob(&m["text"].id).unwrap(),b"ONE\ntwo\nTHREE\n");let config=d.path().join(".git/config");let mut f=fs::OpenOptions::new().append(true).open(&config).unwrap();f.write_all(b"\n[merge \"evil\"]\n  driver = touch escaped\n").unwrap();assert!(g.try_run(&["merge-tree","-z","--write-tree",&a,&b],None).is_err());assert!(!d.path().join("escaped").exists());}

#[test]fn concurrent_git_cas_has_exactly_one_winner(){use std::sync::{Arc,Barrier};let d=repo();let g=Git::open(d.path()).unwrap();let t=g.put_tree(&BTreeMap::new()).unwrap();let a=g.commit_tree(&t,&[],"a").unwrap();let b=g.commit_tree(&t,&[],"b").unwrap();let barrier=Arc::new(Barrier::new(2));let mut ts=Vec::new();for c in [a.clone(),b.clone()]{let g=g.clone();let barrier=barrier.clone();ts.push(std::thread::spawn(move||{barrier.wait();g.advance("refs/heads/race",&c,None)}));}let rs=ts.into_iter().map(|t|t.join().unwrap()).collect::<Vec<_>>();assert_eq!(rs.iter().filter(|x|x.is_ok()).count(),1);assert!(rs.iter().filter_map(|x|x.as_ref().err()).all(|x|x.message.contains("CAS conflict")));let head=g.resolve("refs/heads/race").unwrap().unwrap();assert!(head==a||head==b);}
#[test]fn semantically_integral_json_number_spellings_match_upstream(){let d=tempfile::tempdir().unwrap();fs::create_dir_all(d.path().join(".fugue/log")).unwrap();let mut b=envelope(1,"round",json!({"t":"signal"}));let s=String::from_utf8(b).unwrap().replace("\"seq\":1","\"seq\":1.0");b=s.into_bytes();fs::write(d.path().join(".fugue/log/round.jsonl"),b).unwrap();assert_eq!(journal::read(d.path(),"round").unwrap()[0].seq,1);}

#[test]fn unicode_writer_and_view_list_order_uses_javascript_utf16_order(){let d=repo();let mut v=View::load(d.path(),"round",None).unwrap();v.write("\u{e000}",b"bmp",None).unwrap();v.write("😀",b"astral",None).unwrap();let list=v.list("").unwrap();assert_eq!(list[0]["name"],"😀");assert_eq!(list[1]["name"],"\u{e000}");journal::append(d.path(),"\u{e000}",json!({"t":"signal"})).unwrap();journal::append(d.path(),"😀",json!({"t":"signal"})).unwrap();let rows=journal::merged(d.path()).unwrap();let names=rows.iter().filter(|x|x.seq==1).map(|x|x.writer.as_str()).collect::<Vec<_>>();assert_eq!(names,vec!["round","😀","\u{e000}"]);}

#[test]fn checkpoint_preflight_checks_existing_journal_write_permission_before_cas(){use std::os::unix::fs::PermissionsExt;let d=repo();let g=Git::open(d.path()).unwrap();let mut v=View::load(d.path(),"round",None).unwrap();v.write("file",b"first",None).unwrap();let p=d.path().join(".fugue/log/round.jsonl");let before=fs::read(&p).unwrap();fs::set_permissions(&p,fs::Permissions::from_mode(0o400)).unwrap();let z=v.checkpoint("must not advance");fs::set_permissions(&p,fs::Permissions::from_mode(0o600)).unwrap();assert!(z.is_err());assert!(g.resolve("refs/heads/main").unwrap().is_none());assert_eq!(fs::read(p).unwrap(),before);assert_eq!(v.base,None);}

#[test]
fn explicit_empty_git_directories_remain_visible_until_tombstoned() {
    let d=repo(); let g=Git::open(d.path()).unwrap();
    let empty=g.put_tree(&BTreeMap::new()).unwrap();
    let child=String::from_utf8(g.run(&["mktree","-z"],Some(format!("040000 tree {empty}\tempty\0").as_bytes())).unwrap()).unwrap().trim().to_owned();
    let tree=String::from_utf8(g.run(&["mktree","-z"],Some(format!("040000 tree {empty}\troot-empty\0040000 tree {child}\tnested\0").as_bytes())).unwrap()).unwrap().trim().to_owned();
    let commit=g.commit_tree(&tree,&[],"explicit empty directories").unwrap(); g.advance("refs/heads/main",&commit,None).unwrap();
    let mut v=View::load(d.path(),"round",None).unwrap();
    assert!(v.entries.is_empty(),"the public map remains a leaf map");
    let list=v.list("").unwrap(); assert_eq!(list[0]["name"],"nested"); assert_eq!(list[1]["name"],"root-empty");
    assert_eq!(v.list("nested").unwrap()[0]["name"],"empty"); assert_eq!(v.stat("nested/empty").unwrap()["id"],empty);
    assert!(v.list("nested/empty").unwrap().as_array().unwrap().is_empty());
    assert!(v.write("root-empty",b"cannot replace a directory",None).is_err());
    v.remove("root-empty").unwrap(); assert_eq!(v.list("").unwrap().as_array().unwrap().len(),1);
    v.remove("nested").unwrap(); v.write("nested/new",b"new",None).unwrap();
    assert_eq!(v.list("nested").unwrap()[0]["name"],"new"); assert!(v.stat("nested/empty").unwrap().is_null());
    assert_eq!(View::load(d.path(),"round",None).unwrap().list("").unwrap(),v.list("").unwrap());
}

#[test]
fn metadata_batch_preserves_order_duplicates_and_type_validation() {
    let d=repo(); let g=Git::open(d.path()).unwrap();
    let a=g.put_blob(b"abc").unwrap(); let b=g.put_blob(b"x\0\xffy").unwrap(); let tree=g.put_tree(&BTreeMap::new()).unwrap();
    assert_eq!(g.blob_sizes(&[&b,&a,&b]).unwrap(),[4,3,4]);
    assert_eq!(g.clone().blob_sizes(&[&a,&b]).unwrap(),[3,4]);
    assert!(g.blob_sizes(&[]).unwrap().is_empty());
    assert!(g.blob_sizes(&[&a,&tree]).is_err());
    assert!(g.blob_sizes(&[&a,&"f".repeat(40)]).is_err());
    for id in ["HEAD","--help","deadbeef","0\n1"] { assert!(g.blob_size(id).is_err()); }
    assert!(g.blob_size(&"a".repeat(64)).is_err());
    assert!(!d.path().join(".git/index").exists());
}

#[test]
fn stat_and_list_measure_blobs_larger_than_the_body_read_budget() {
    let d=repo(); let path=d.path().join("large-host-file"); let length=util::MAX_BYTES as u64+1;
    fs::File::create(&path).unwrap().set_len(length).unwrap();
    let out=Command::new("git").arg("-C").arg(d.path()).args(["hash-object","-w","--"]).arg(&path).output().unwrap();
    assert!(out.status.success(),"{}",String::from_utf8_lossy(&out.stderr));
    let id=String::from_utf8(out.stdout).unwrap().trim().to_owned(); let g=Git::open(d.path()).unwrap();
    let entries=BTreeMap::from([("large".into(),Entry{kind:"file".into(),mode:0o100644,id:id.clone()}),("same-object".into(),Entry{kind:"file".into(),mode:0o100755,id:id.clone()})]);
    let tree=g.put_tree(&entries).unwrap(); let commit=g.commit_tree(&tree,&[],"large lower blobs").unwrap(); g.advance("refs/heads/main",&commit,None).unwrap();
    let v=View::load(d.path(),"round",None).unwrap();
    assert_eq!(v.stat("large").unwrap()["size"],length);
    let list=v.list("").unwrap(); assert_eq!(list[0]["size"],length); assert_eq!(list[1]["size"],length);
    assert!(v.read("large").is_err(),"metadata access must not widen body-read limits");
    assert_eq!(fs::metadata(&path).unwrap().len(),length); assert!(!d.path().join(".git/index").exists()); assert!(!d.path().join(".fugue").exists());
}
