//! Hostile Git control-plane metadata must never redirect writes or reads outside the repository.
use fugue::git::Git;
use std::{fs,process::Command};
use std::os::unix::fs::symlink;
fn repo()->tempfile::TempDir{let d=tempfile::tempdir().unwrap();assert!(Command::new("/usr/bin/git").args(["init","-q","-b","main"]).arg(d.path()).status().unwrap().success());d}
#[test]fn object_directory_symlink_cannot_redirect_blob_publication(){let d=repo();let outside=tempfile::tempdir().unwrap();fs::remove_dir_all(d.path().join(".git/objects")).unwrap();symlink(outside.path(),d.path().join(".git/objects")).unwrap();assert!(Git::open(d.path()).is_err());assert!(fs::read_dir(outside.path()).unwrap().next().is_none());}
#[test]fn metadata_replacement_after_open_is_rechecked_before_mutation(){let d=repo();let g=Git::open(d.path()).unwrap();let outside=tempfile::tempdir().unwrap();fs::remove_dir_all(d.path().join(".git/objects")).unwrap();symlink(outside.path(),d.path().join(".git/objects")).unwrap();assert!(g.put_blob(b"must stay local").is_err());assert!(fs::read_dir(outside.path()).unwrap().next().is_none());}
#[test]fn nested_refs_and_logs_symlinks_are_denied(){for target in ["refs/heads","logs/refs/heads"]{let d=repo();let outside=tempfile::tempdir().unwrap();let p=d.path().join(".git").join(target);if p.exists(){fs::remove_dir_all(&p).unwrap()}fs::create_dir_all(p.parent().unwrap()).unwrap();symlink(outside.path(),&p).unwrap();assert!(Git::open(d.path()).is_err(),"{target}");assert!(fs::read_dir(outside.path()).unwrap().next().is_none());}}
#[test]fn foreign_object_alternates_and_common_directory_are_refused(){for name in ["objects/info/alternates","commondir"]{let d=repo();let outside=tempfile::tempdir().unwrap();let p=d.path().join(".git").join(name);fs::create_dir_all(p.parent().unwrap()).unwrap();fs::write(p,outside.path().to_str().unwrap()).unwrap();assert!(Git::open(d.path()).is_err(),"{name}");}}
#[test]fn local_config_include_is_refused_without_disclosing_foreign_contents(){for section in ["[include]","[includeIf \"gitdir:**\"]","[ Include ]"]{let d=repo();let outside=tempfile::tempdir().unwrap();let secret=outside.path().join("secret-config");fs::write(&secret,b"SECRET-NOT-CONFIG\n").unwrap();let config=d.path().join(".git/config");let mut b=fs::read(&config).unwrap();b.extend_from_slice(format!("\n{section}\npath = {}\n",secret.display()).as_bytes());fs::write(config,b).unwrap();let e=Git::open(d.path()).unwrap_err();assert!(!e.message.contains("SECRET-NOT-CONFIG"));}}
#[test]fn control_file_hardlinks_and_special_files_are_denied(){let d=repo();let outside=tempfile::tempdir().unwrap();let cfg=d.path().join(".git/config");fs::hard_link(&cfg,outside.path().join("config-alias")).unwrap();assert!(Git::open(d.path()).is_err());let d=repo();let fifo=d.path().join(".git/packed-refs");let name=std::ffi::CString::new(fifo.to_str().unwrap()).unwrap();assert_eq!(unsafe{libc::mkfifo(name.as_ptr(),0o600)},0);assert!(Git::open(d.path()).is_err());}
#[test]fn ordinary_packed_repository_and_sha256_remain_supported(){for format in ["sha1","sha256"]{let d=tempfile::tempdir().unwrap();assert!(Command::new("/usr/bin/git").args(["init","-q","-b","main"]).arg(format!("--object-format={format}")).arg(d.path()).status().unwrap().success());let g=Git::open(d.path()).unwrap();let t=g.put_tree(&Default::default()).unwrap();let id=g.commit_tree(&t,&[],"base").unwrap();g.advance("refs/heads/main",&id,None).unwrap();assert!(Command::new("/usr/bin/git").arg("-C").arg(d.path()).args(["gc","--quiet"]).status().unwrap().success());let g=Git::open(d.path()).unwrap();assert_eq!(g.resolve("main").unwrap().as_deref(),Some(id.as_str()));assert!(g.put_blob(b"new after pack").is_ok());}}
#[test]fn filtered_hash_requests_and_merge_renormalization_cannot_execute_host_helpers(){let d=repo();let g=Git::open(d.path()).unwrap();let marker=d.path().join("filter-executed");assert!(Command::new("/usr/bin/git").arg("-C").arg(d.path()).args(["config","filter.evil.clean"]).arg(format!("touch {}; cat",marker.display())).status().unwrap().success());fs::write(d.path().join(".gitattributes"),b"file filter=evil\n").unwrap();assert!(g.run(&["hash-object","-w","--stdin","--path=file"],Some(b"body")).is_err());assert!(!marker.exists());let attr=g.put_blob(b"file filter=evil\n").unwrap();let mut map=std::collections::BTreeMap::new();map.insert(".gitattributes".into(),fugue::git::Entry{kind:"file".into(),mode:0o100644,id:attr});let mut make=|body:&[u8],parent:&[String]|{map.insert("file".into(),fugue::git::Entry{kind:"file".into(),mode:0o100644,id:g.put_blob(body).unwrap()});let t=g.put_tree(&map).unwrap();g.commit_tree(&t,parent,"merge fixture").unwrap()};let b=make(b"a\nb\nc\n",&[]);let x=make(b"A\nb\nc\n",&[b.clone()]);let y=make(b"a\nb\nC\n",&[b]);assert!(Command::new("/usr/bin/git").arg("-C").arg(d.path()).args(["config","merge.renormalize","true"]).status().unwrap().success());assert_eq!(g.try_run(&["merge-tree","-z","--write-tree",&x,&y],None).unwrap().0,0);assert!(!marker.exists());}
#[test]fn malformed_git_config_errors_never_echo_values(){let d=repo();let config=d.path().join(".git/config");let mut b=fs::read(&config).unwrap();b.extend_from_slice(b"\n[core]\n bare = PRIVATE-SENTINEL-NOT-A-BOOL\n");fs::write(config,b).unwrap();let error=Git::open(d.path()).unwrap_err();assert!(!error.message.contains("PRIVATE-SENTINEL"));}

#[test]fn abbreviated_git_helper_flags_cannot_bypass_the_allowlist(){let d=repo();let g=Git::open(d.path()).unwrap();let marker=d.path().join("filter-marker");assert!(Command::new("/usr/bin/git").arg("-C").arg(d.path()).args(["config","filter.evil.clean"]).arg(format!("touch {}; cat",marker.display())).status().unwrap().success());fs::write(d.path().join(".gitattributes"),b"file filter=evil\n").unwrap();for flag in ["--pa=file","--pat=file","--p=file","--path=file","--stdin-pa","--stdin-paths"]{assert!(g.run(&["hash-object","-w","--stdin",flag],Some(b"body")).is_err(),"{flag}");assert!(!marker.exists());}for flag in ["--fil","--textc","--use-mail","--ext-d"]{assert!(g.try_run(&["cat-file",flag,"HEAD:file"],None).is_err(),"{flag}");}assert!(g.put_blob(b"ordinary exact shape").is_ok());}
