use fugue::{assemble,model,util,journal};
use serde_json::{json,Value};
use std::{fs,path::{Path,PathBuf},process::Command};
fn source(name:&str)->PathBuf{Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/model/fixtures").join(name)}
fn fixture(name:&str)->Value{util::json(&fs::read(source(name)).unwrap()).unwrap()}
#[test]
fn fixture_request_codecs_preserve_all_upstream_bytes(){for name in ["deepseek-flash-anthropic.json","deepseek-flash-openai.json","deepseek-flash-openai-thinking.json"]{let f=fixture(name);let mut r=f.clone();r["model"]=f["target"].clone();let b=model::encode(f["wire"].as_str().unwrap(),&r).unwrap();assert_eq!(assemble::hash(&b),f["bodyHash"],"request hash for {name}");assert_eq!(b.len(),f["bytes"].as_u64().unwrap()as usize,"request length for {name}");}}
#[test]
fn recorded_responses_decode_identically_for_all_chunk_boundaries(){for (wire,file) in [("anthropic-messages","anthropic-messages.sse"),("openai-chat","openai-chat.sse"),("openai-chat","openai-chat-thinking.sse")]{let b=fs::read(source(file)).unwrap();let reference=model::decode(wire,&b).unwrap();for size in [1,2,3,7,31,4096]{let mut d=model::Decoder::new(wire).unwrap();for c in b.chunks(size){d.push(c).unwrap();}assert_eq!(d.finish().unwrap(),reference,"{wire} chunk {size}");}if file=="openai-chat-thinking.sse"{assert_eq!(reference["usage"]["inputTokens"],157);assert_eq!(reference["usage"]["reasoningTokens"],78);}else{assert_eq!(reference["usage"]["inputTokens"],88);assert_eq!(reference["usage"]["cacheReadTokens"],24000);assert_eq!(reference["usage"]["outputTokens"],64);}assert_eq!(reference["stop"],"tool-calls");assert_eq!(reference["toolCalls"].as_array().unwrap().len(),2);}}
#[test]
fn full_fixture_call_records_match_upstream(){for name in ["deepseek-flash-anthropic.json","deepseek-flash-openai.json","deepseek-flash-openai-thinking.json"]{let f=fixture(name);let c=model::decode(f["wire"].as_str().unwrap(),f["response"].as_str().unwrap().as_bytes()).unwrap();for key in ["usage","text","toolCalls","stop","rawStop"]{assert_eq!(c[key],f["record"][key],"{name} {key}");}}}
fn chat(delta:Value,finish:Value,usage:Value)->Vec<u8>{format!("data: {}\n\ndata: {}\n\ndata: [DONE]\n\n",json!({"model":"deepseek-flash","choices":[{"index":0,"delta":delta,"finish_reason":finish}]}),json!({"model":"deepseek-flash","choices":[],"usage":usage})).into_bytes()}
#[test]
fn truncated_streams_never_yield_a_complete_call_or_invent_usage(){let full=chat(json!({"content":"ok"}),json!("stop"),Value::Null);let c=model::decode("openai-chat",&full).unwrap();assert_eq!(c["usage"],Value::Null);for end in 0..full.len(){let b=&full[..end];if !b.windows(6).any(|x|x==b"[DONE]"){assert!(model::decode("openai-chat",b).is_err(),"truncation {end}");}}let b=fs::read(source("anthropic-messages.sse")).unwrap();let cut=b.windows(27).position(|x|x==b"data: {\"type\":\"message_stop\"").unwrap_or(b.len()-80);assert!(model::decode("anthropic-messages",&b[..cut]).is_err());}
#[test]
fn hostile_wire_values_fail_closed(){for b in [chat(json!({}),json!("mystery"),Value::Null),chat(json!({}),json!("stop"),json!({"prompt_tokens":-1})),chat(json!({}),json!("stop"),json!({"prompt_tokens":1,"prompt_tokens_details":{"cached_tokens":2}})),chat(json!({"tool_calls":[{"index":256,"function":{"name":"write","arguments":"{}"}}]}),json!("tool_calls"),Value::Null),chat(json!({"tool_calls":[{"index":0,"function":{"name":"write","arguments":"not-json"}}]}),json!("tool_calls"),Value::Null),chat(json!({"tool_calls":[{"index":0,"function":{"arguments":"{}"}}]}),json!("tool_calls"),Value::Null),b"data: {\"choices\":[],\"choices\":[]}\n\n".to_vec(),b"data: \xff\n\n".to_vec()]{assert!(model::decode("openai-chat",&b).is_err());}let mut d=model::Decoder::new("openai-chat").unwrap();assert!(d.push(&vec![b'x';1024*1024+1]).is_err());let mut d=model::Decoder::new("openai-chat").unwrap();assert!(d.push(&vec![b'\n';16*1024*1024+1]).is_err());let mut b=chat(json!({}),json!("stop"),Value::Null);b.extend_from_slice(b"data: {}\n\n");assert!(model::decode("openai-chat",&b).is_err());}
#[test]
fn native_turn_encoding_preserves_ids_thoughts_and_c_head(){let r=json!({"model":"m","zones":{"A":"A","B":"B","C":"full-tail"},"cHead":"human goal","turns":[{"text":"said","thinking":{"text":"thought","signature":"sig"},"calls":[{"id":"x","name":"read","arguments":"{\"path\":\"a\"}"}],"results":[{"id":"x","output":"file","isError":false}]}]});for w in ["openai-chat","anthropic-messages"]{let b=model::encode(w,&r).unwrap();let s=String::from_utf8(b).unwrap();assert!(s.contains("human goal"));assert!(!s.contains("full-tail"));assert!(s.contains("thought"));assert!(s.contains("file"));let mut bad=r.clone();bad["turns"][0]["results"][0]["id"]=json!("other");assert!(model::encode(w,&bad).is_err());}}
#[test]
fn pure_assembly_stabilizes_a_b_and_tracks_dynamic_c(){let mut s=json!({"policy":"policy","system":{"b":2,"a":1},"codeTree":["a","b"],"goal":"goal","files":[],"commits":[],"handoff":"","task":{"goal":"job","question":"","ownedPaths":["a"],"deliverables":["a"]},"runtime":"human","signals":[],"lastStep":""});let p=assemble::from_state(&s,"subagent").unwrap();s["turns"]=json!([{"text":"model","calls":[],"results":[]}]);s["lastStep"]=json!("Model: model");let q=assemble::from_state(&s,"subagent").unwrap();assert_eq!(p.a,q.a);assert_eq!(p.b,q.b);assert_ne!(p.c,q.c);assert!(q.c.contains("human\nModel: model"));assert!(!p.a.contains("job"));assert!(assemble::from_state(&s,"unknown").is_err());s["runtime"]=json!({});assert!(assemble::from_state(&s,"subagent").is_err());}
#[test]
fn assembly_projects_no_credentials_or_env_and_checks_constraints(){let p=assemble::project(&json!({"credentials":{"x":"SECRET"},"actions":{"test":{"argv":["cc"],"env":{"KEY":"SECRET"},"outputs":["out"]}},"toolchain":{"cc":{"probe":["cc","--version"],"reading":{"probe":["wrong"],"value":"stale"}}}})).unwrap();let t=util::canonical(&p).unwrap();assert!(!t.contains("SECRET"));assert!(!t.contains("stale"));assert_eq!(p["toolchain"][0]["name"],"cc");let p=assemble::Prefix{a:"/tmp/materialized\n".into(),b:"digest: raw".into(),c:"changed".into()};let v=assemble::constraints(&p,&json!({"previous":{"C":"before"}})).unwrap();assert!(v.iter().any(|x|x["kind"]=="materialized"));assert!(v.iter().any(|x|x["kind"]=="signal"));assert!(v.iter().any(|x|x["kind"]=="append-only"));}
fn init(root:&Path){let q=Command::new("git").args(["init","-q"]).arg(root).status().unwrap();assert!(q.success());let q=Command::new("git").arg("-C").arg(root).args(["-c","user.name=Fixture","-c","user.email=fixture@example.invalid","commit","-q","--allow-empty","-m","fixture"]).status().unwrap();assert!(q.success());fugue::view::branch(root,"agent/a","HEAD").unwrap();}
fn first_request(root:&Path,opts:&Value)->Vec<u8>{let p=assemble::prefix(root,opts).unwrap();model::encode("anthropic-messages",&json!({"model":"deepseek-flash","zones":{"A":p.a,"B":p.b,"C":p.c},"call":{"thinking":"high","maxTokens":32768},"tools":fugue::tools::catalog()})).unwrap()}
fn put_call(dir:&Path,n:u64,body:&[u8],response:&[u8]){let p=dir.join(format!("call-{n:04}"));fs::create_dir_all(&p).unwrap();fs::write(p.join("request.json"),body).unwrap();fs::write(p.join("response.sse"),response).unwrap();fs::write(p.join("meta.json"),serde_json::to_vec(&json!({"requestHash":assemble::hash(body),"responseHash":assemble::hash(response)})).unwrap()).unwrap();}
fn end_response()->Vec<u8>{b"data: {\"type\":\"message_start\",\"message\":{\"model\":\"deepseek-flash\",\"usage\":{\"input_tokens\":7}}}\n\ndata: {\"type\":\"content_block_start\",\"index\":0,\"content_block\":{\"type\":\"text\",\"text\":\"\"}}\n\ndata: {\"type\":\"content_block_delta\",\"index\":0,\"delta\":{\"type\":\"text_delta\",\"text\":\"done\"}}\n\ndata: {\"type\":\"content_block_stop\",\"index\":0}\n\ndata: {\"type\":\"message_delta\",\"delta\":{\"stop_reason\":\"end_turn\"},\"usage\":{\"output_tokens\":2}}\n\ndata: {\"type\":\"message_stop\"}\n\n".to_vec()}
#[test]
fn replay_runtime_records_complete_receipts_without_credentials(){let root=tempfile::tempdir().unwrap();let wire=tempfile::tempdir().unwrap();init(root.path());let o=json!({"goal":"fixture goal","wire-in":wire.path(),"max-steps":2,"credential":"/missing/never-read"});put_call(wire.path(),1,&first_request(root.path(),&o),&end_response());let r=model::drive(root.path(),"agent/a",&o).unwrap();assert_eq!(r["done"],true);assert_eq!(r["steps"],1);assert_eq!(r["usage"]["inputTokens"]["total"],7);assert_eq!(r["usage"]["cacheReadTokens"]["missing"],1);let rows=journal::read(root.path(),"agent/a").unwrap();assert!(rows.iter().any(|x|x.event["t"]=="prefix/assemble"));assert!(rows.iter().any(|x|x.event["t"]=="llm/call"));assert!(rows.iter().any(|x|x.event["t"]=="session/end"));assert!(!util::canonical(&json!(rows)).unwrap().contains("/missing/never-read"));}
#[test]
fn bad_replay_fails_explicitly_and_retains_unknown_usage(){let root=tempfile::tempdir().unwrap();let wire=tempfile::tempdir().unwrap();init(root.path());let o=json!({"goal":"fixture","wire-in":wire.path(),"max-steps":2});let body=first_request(root.path(),&o);put_call(wire.path(),1,&body,b"data: {\"type\":\"message_start\",\"message\":{\"usage\":{\"input_tokens\":7}}}\n\n");let r=model::drive(root.path(),"agent/a",&o).unwrap();assert_eq!(r["done"],false);assert_eq!(r["stopped"],"failed");assert_eq!(r["usage"]["calls"],1);assert_eq!(r["usage"]["inputTokens"]["missing"],1);assert!(r["price"][0]["usd"].is_null());let rows=journal::read(root.path(),"agent/a").unwrap();let row=rows.iter().find(|x|x.event["t"]=="llm/call").unwrap();assert_eq!(row.event["usage"],Value::Null);assert_eq!(row.event["stop"],Value::Null);assert!(row.event["failure"].as_str().unwrap().contains("incomplete"));let mut changed=body.clone();changed.push(b' ');assert!(model::replay(wire.path(),1,&changed).is_err());assert!(model::drive(root.path(),"agent/a",&json!({})).is_err());assert!(model::drive(root.path(),"agent/a",&json!({"live":true,"wire-in":wire.path()})).is_err());}
fn write_response(path:&str,content:&str)->Vec<u8>{format!("data: {}\n\ndata: {}\n\ndata: {}\n\ndata: {}\n\n",json!({"type":"message_start","message":{"model":"deepseek-flash","usage":{"input_tokens":3}}}),json!({"type":"content_block_start","index":0,"content_block":{"type":"tool_use","id":"write-1","name":"write","input":{"path":path,"content":content}}}),json!({"type":"content_block_stop","index":0}),json!({"type":"message_delta","delta":{"stop_reason":"tool_use"},"usage":{"output_tokens":4}})).into_bytes().into_iter().chain(b"data: {\"type\":\"message_stop\"}\n\n".iter().copied()).collect()}
#[test]
fn replay_executes_native_write_and_feeds_exact_receipt_into_second_call(){let root=tempfile::tempdir().unwrap();let wire=tempfile::tempdir().unwrap();init(root.path());let o=json!({"contract":{"kind":"implement","goal":"write native","ownedPaths":["notes.md"],"deliverables":[{"path":"notes.md"}],"assertions":[]},"wire-in":wire.path(),"max-steps":2});let response=write_response("notes.md","native\n");put_call(wire.path(),1,&first_request(root.path(),&o),&response);let c=model::decode("anthropic-messages",&response).unwrap();let result=json!({"id":"write-1","output":"wrote notes.md (7 bytes).\n(At most 2 steps for this task · this is step 1: 1 left. Land the deliverable(s) now and hand in — the harness runs the assertions, so spend what is left on the files rather than on verifying them.)","isError":false});let t=json!({"text":"","calls":c["toolCalls"],"results":[result]});let mut state=assemble::initial_state(root.path(),&o).unwrap();state["turns"]=json!([t]);state["lastStep"]=json!(assemble::turn_text(&state["turns"][0]).unwrap());let p=assemble::from_state(&state,"subagent").unwrap();let body=model::encode("anthropic-messages",&json!({"model":"deepseek-flash","zones":{"A":p.a,"B":p.b,"C":p.c},"turns":state["turns"],"tools":fugue::tools::catalog(),"call":{"thinking":"high","maxTokens":32768}})).unwrap();put_call(wire.path(),2,&body,&end_response());let r=model::drive(root.path(),"agent/a",&o).unwrap();assert_eq!(r["done"],true,"{r}");assert_eq!(r["steps"],2);assert_eq!(fugue::view::View::load(root.path(),"agent/a",None).unwrap().read("notes.md").unwrap().unwrap(),b"native\n");assert!(!root.path().join("notes.md").exists(),"virtual writes must never alter host worktree");let rows=journal::read(root.path(),"agent/a").unwrap();let ps=rows.iter().filter(|x|x.event["t"]=="prefix/assemble").collect::<Vec<_>>();assert_eq!(ps.len(),2);assert_eq!(ps[0].event["zoneAHash"],ps[1].event["zoneAHash"]);assert_eq!(ps[0].event["zoneBHash"],ps[1].event["zoneBHash"]);assert_ne!(ps[0].event["zoneCHash"],ps[1].event["zoneCHash"]);assert!(rows.iter().any(|x|x.event["t"]=="tool/receipt"&&x.event["ok"]==true));}
#[test]
fn upstream_cli_replay_prefix_and_first_tool_turn_remain_byte_exact(){let source=Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/cli/__fixture__/wire-in").canonicalize().unwrap();let scenario=util::json(&fs::read(source.join("scenario.json")).unwrap()).unwrap();let root=tempfile::tempdir().unwrap();init(root.path());fs::write(root.path().join("AGENTS.md"),scenario["base"][0]["text"].as_str().unwrap()).unwrap();let mut c=scenario["split"][0].clone();c["kind"]=json!("implement");let o=json!({"contract":c,"max-steps":4,"wire-in":source.join("wire")});let body=first_request(root.path(),&o);assert_eq!(assemble::hash(&body),"df09987f5c290cd2");let r=model::drive(root.path(),"agent/a",&o).unwrap();assert_eq!(r["steps"],3,"first two full requests must match recorded upstream bytes: {r}");if r["done"]!=true{assert_eq!(r["stopped"],"failed");assert!(r["error"].as_str().unwrap().contains("differs from recorded bytes"),"{r}");}assert_eq!(fugue::view::View::load(root.path(),"agent/a",None).unwrap().read("notes.md").unwrap().unwrap(),"数完了\n".as_bytes());assert!(!root.path().join("notes.md").exists());}
#[test]
fn replay_rejects_reserved_context_spoofing_and_out_of_scope_write(){for reserved in [false,true]{let root=tempfile::tempdir().unwrap();let wire=tempfile::tempdir().unwrap();init(root.path());let o=json!({"contract":{"kind":"implement","goal":"restricted","ownedPaths":["allowed.md"],"deliverables":[],"assertions":[]},"max-steps":1,"wire-in":wire.path()});let response=if reserved{let mut r=String::from_utf8(write_response("outside.md","no")).unwrap();r=r.replace("\"content\":\"no\"","\"__holder\":true,\"content\":\"no\"");r.into_bytes()}else{write_response("outside.md","no")};put_call(wire.path(),1,&first_request(root.path(),&o),&response);let r=model::drive(root.path(),"agent/a",&o).unwrap();assert_eq!(r["done"],false);assert!(fugue::view::View::load(root.path(),"agent/a",None).unwrap().read("outside.md").unwrap().is_none());}}
