use fugue::{sandbox,tools,view,journal,util};
use serde_json::{json,Value};
use sha2::{Digest,Sha256};
use std::{fs,path::Path,process::Command};
use std::os::unix::fs::{MetadataExt,symlink};
fn git(root:&Path,args:&[&str]){let r=Command::new("/usr/bin/git").args(["-c","core.hooksPath=/dev/null","-c","user.name=Test","-c","user.email=test@example.invalid"]).args(args).current_dir(root).env_remove("GIT_DIR").env_remove("GIT_WORK_TREE").env_remove("GIT_INDEX_FILE").output().unwrap();assert!(r.status.success(),"git failed: {}",String::from_utf8_lossy(&r.stderr));}
fn repo()->tempfile::TempDir{let d=tempfile::tempdir().unwrap();git(d.path(),&["init","-b","main"]);fs::create_dir(d.path().join("src")).unwrap();fs::write(d.path().join("src/a.txt"),"one\ntwo\none\n").unwrap();fs::write(d.path().join("root.rs"),"fn main() {}\n").unwrap();git(d.path(),&["add","."]);git(d.path(),&["commit","-m","base"]);view::branch(d.path(),"agent/test","main").unwrap();fs::create_dir(d.path().join(".fugue")).unwrap();d}
fn invoke(root:&Path,name:&str,args:Value)->Value{tools::invoke(root,"agent/test",name,&args).unwrap()}
#[test]fn catalog_is_exact_upstream_stable_protocol(){let c=tools::catalog();assert_eq!(c.as_array().unwrap().len(),12);let b=util::canonical(&c).unwrap();assert_eq!(&format!("{:x}",Sha256::digest(b.as_bytes()))[..16],"5681832878aa0634");assert_eq!(c,tools::catalog());}
#[test]fn tools_validate_scope_and_preserve_mode(){let d=repo();let r=d.path();let mut v=view::View::load(r,"agent/test",None).unwrap();v.chmod("root.rs",0o755).unwrap();assert_eq!(invoke(r,"write",json!({"path":"root.rs","content":"new","__contract":{"ownedPaths":["src"]}}))["ok"],false);assert_eq!(invoke(r,"write",json!({"path":"root.rs","content":"new"}))["ok"],true);assert_eq!(view::View::load(r,"agent/test",None).unwrap().entries["root.rs"].mode,0o100755);assert_eq!(invoke(r,"edit",json!({"path":"src/a.txt","old_string":"one","new_string":"ONE"}))["ok"],false);assert_eq!(invoke(r,"edit",json!({"path":"src/a.txt","old_string":"one","new_string":"ONE","replace_all":true}))["ok"],true);assert!(invoke(r,"read",json!({"path":"./src/../src/a.txt","offset":2,"limit":1}))["output"].as_str().unwrap().ends_with("2\ttwo"));assert_eq!(invoke(r,"write",json!({"path":"other","content":"no","__contract":{"ownedPaths":[]}}))["ok"],false);}
#[test]fn tools_reject_unknown_fields_and_path_escapes(){let d=repo();for p in ["/etc/passwd","../escape","src/../../escape",".git/config","src/.fugue/x","src\\x"]{assert_eq!(invoke(d.path(),"write",json!({"path":p,"content":"bad"}))["ok"],false)}assert_eq!(invoke(d.path(),"write",json!({"path":"a","content":"x","unknown":true}))["ok"],false);assert_eq!(invoke(d.path(),"undeclared",json!({}))["ok"],false);let mut v=view::View::load(d.path(),"agent/test",None).unwrap();v.symlink("link","src").unwrap();assert_eq!(invoke(d.path(),"read",json!({"path":"link/a.txt"}))["ok"],false);assert!(journal::read(d.path(),"agent/test").unwrap().iter().any(|r|r.event["t"]=="bound/deny"));}
#[test]fn glob_and_grep_work_without_shell_or_symlink_following(){let d=repo();let r=invoke(d.path(),"glob",json!({"pattern":"**/*.rs"}));assert!(r["output"].as_str().unwrap().contains("root.rs"));let r=invoke(d.path(),"grep",json!({"pattern":"one","glob":"src/**","output_mode":"count"}));assert!(r["output"].as_str().unwrap().contains("src/a.txt:2"));assert_eq!(invoke(d.path(),"grep",json!({"pattern":"(?=a)"}))["ok"],false);}
#[test]fn holder_logs_are_receipts_and_child_cannot_open_gate(){let d=repo();let r=d.path();assert_eq!(invoke(r,"exit_plan_mode",json!({"plan":"done"}))["ok"],false);let r1=invoke(r,"todo_write",json!({"todos":[{"content":"work","status":"in_progress"}]}));assert_eq!(r1["ok"],true);let r2=invoke(r,"ask_user_question",json!({"questions":[{"question":"Which?","options":[{"label":"a"}]}],"__holder":true}));assert_eq!(r2["halt"],true);let rows=journal::read(r,"agent/test").unwrap();for row in rows.iter().filter(|r|r.event["t"].as_str().unwrap_or("").starts_with("holder/")){let b=row.event["body"].as_str().unwrap();assert_eq!(row.event["digest"],&format!("{:x}",Sha256::digest(b.as_bytes()))[..16]);}}
#[test]fn immutable_fork_incremental_ensure_verify_and_dispose(){let d=repo();let r=d.path();fs::write(r.join("root.rs"),"dirty host file").unwrap();let fork=sandbox::fork(r,"agent/test","main",&json!({"strategy":"copy"})).unwrap();let merged=Path::new(fork["merged"].as_str().unwrap());assert_eq!(fs::read_to_string(merged.join("root.rs")).unwrap(),"fn main() {}\n");assert!(!merged.join(".git").exists());assert!(!merged.join(".fugue").exists());assert_eq!(sandbox::verify(r,"agent/test").unwrap()["ok"],true);let before=fs::metadata(merged.join("root.rs")).unwrap();let mut v=view::View::load(r,"agent/test",None).unwrap();v.write("src/a.txt",b"changed",None).unwrap();sandbox::ensure(r,"agent/test",None).unwrap();let after=fs::metadata(merged.join("root.rs")).unwrap();assert_eq!(before.ino(),after.ino());assert_eq!(before.mtime_nsec(),after.mtime_nsec());assert_eq!(sandbox::verify(r,"agent/test").unwrap()["ok"],true);let rows=journal::read(r,"agent/test").unwrap().len();sandbox::ensure(r,"agent/test",None).unwrap();assert_eq!(journal::read(r,"agent/test").unwrap().len(),rows);fs::write(merged.join("rogue"),"bad").unwrap();assert_eq!(sandbox::verify(r,"agent/test").unwrap()["ok"],false);assert!(sandbox::ensure(r,"agent/test",None).is_err());sandbox::dispose(r,"agent/test").unwrap();assert!(!merged.exists());sandbox::dispose(r,"agent/test").unwrap();assert_eq!(fs::read_to_string(r.join("root.rs")).unwrap(),"dirty host file");}
#[test]fn materializer_never_traverses_external_symlinks(){let d=repo();let outside=tempfile::tempdir().unwrap();let sentinel=outside.path().join("keep");fs::write(&sentinel,"secret").unwrap();let mat=d.path().join(".fugue/mat/agent/test");fs::create_dir_all(&mat).unwrap();symlink(outside.path(),mat.join("merged")).unwrap();sandbox::dispose(d.path(),"agent/test").unwrap();assert_eq!(fs::read_to_string(&sentinel).unwrap(),"secret");let mut v=view::View::load(d.path(),"agent/test",None).unwrap();v.symlink("unsafe","../../outside").unwrap();sandbox::fork(d.path(),"agent/test","main",&json!({})).unwrap();assert!(sandbox::ensure(d.path(),"agent/test",None).is_err());assert_eq!(fs::read_to_string(&sentinel).unwrap(),"secret");}
#[test]fn diffstat_baselines_are_outside_tree_and_symlinks_are_leaves(){let d=repo();let f=sandbox::fork(d.path(),"agent/test","main",&json!({})).unwrap();let dir=f["merged"].as_str().unwrap();let outside=tempfile::tempdir().unwrap();let base=outside.path().join("base.json");sandbox::diff_stat(d.path(),"agent/test",&json!({"save":base})).unwrap();let unchanged=sandbox::diff_stat(d.path(),"agent/test",&json!({"baseline":base})).unwrap();assert_eq!(unchanged["count"],0);fs::write(Path::new(dir).join("root.rs"),"altered").unwrap();let changed=sandbox::diff_stat(d.path(),"agent/test",&json!({"baseline":base})).unwrap();assert_eq!(changed["count"],1);assert!(sandbox::diff_stat(d.path(),"agent/test",&json!({"save":Path::new(dir).join("bad.json")})).is_err());}
#[test]fn execution_is_kernel_isolated_or_fail_closed_without_side_effects(){let d=repo();let outside=tempfile::tempdir().unwrap();let sentinel=outside.path().join("host-write");let command=format!("printf forbidden > '{}'",sentinel.display());let p=sandbox::policy(d.path(),None,&json!({})).unwrap();let r=sandbox::execute(d.path(),"agent/test",&["/bin/sh".into(),"-c".into(),command],&json!({})).unwrap();assert!(!sentinel.exists());if p["available"]==false{assert_eq!(r["denied"],true);assert_eq!(r["exit"],126);assert!(r["stderr"].as_str().unwrap().contains("no command was executed"));}else{assert_ne!(r["exit"],0);assert_eq!(r["denied"],true);}let rows=journal::read(d.path(),"agent/test").unwrap();assert!(rows.iter().any(|r|r.event["t"]=="run/start"));assert!(rows.iter().any(|r|r.event["t"]=="run/end"));}
#[test]fn action_environment_network_and_output_shapes_fail_before_execution(){let d=repo();for (name,binding) in [("badenv",json!({"argv":["true"],"env":{"LD_PRELOAD":"/work/evil"}})),("badpath",json!({"argv":["true"],"outputs":["../outside"]})),("badnet",json!({"argv":["true"],"net":"anything"})),("unknown",json!({"argv":["true"],"privileged":true}))]{let cfg=json!({"actions":{name:binding}});fs::write(d.path().join(".fugue/config"),serde_json::to_vec(&cfg).unwrap()).unwrap();assert!(sandbox::run(d.path(),"agent/test",name,&[],&json!({})).is_err());}let f=sandbox::fork(d.path(),"agent/test","main",&json!({"strategy":"overlayfs"})).unwrap();assert_eq!(f["strategy"],"copy");assert!(f["why"].as_str().unwrap().contains("skipped overlayfs"));}
#[test]fn native_guard_self_test_installs_layers_or_refuses_unavailable_kernel(){let r=Command::new(env!("CARGO_BIN_EXE_fugue")).args(["__fugue-guard","--probe"]).output().unwrap();if r.status.success(){assert_eq!(r.stdout,b"fugue-guard-v1\n");}else{assert_eq!(r.status.code(),Some(126));assert!(String::from_utf8_lossy(&r.stderr).contains("guard refused"));}}
#[test]fn receipts_stay_utf8_and_explicitly_report_truncation(){let d=repo();let big="字".repeat(10_000);assert_eq!(invoke(d.path(),"write",json!({"path":"large","content":big}))["ok"],true);let r=invoke(d.path(),"read",json!({"path":"large"}));let s=r["output"].as_str().unwrap();assert!(s.len()<8500);assert!(s.contains("bytes omitted"));assert!(!s.contains('\u{fffd}'));}
#[test]fn resolve_and_investigate_scopes_are_separate_defensive_contracts(){let d=repo();let yes=invoke(d.path(),"write",json!({"path":"src/a.txt","content":"resolution","__contract":{"kind":"resolve","conflictPaths":["src/a.txt"]}}));assert_eq!(yes["ok"],true);let no=invoke(d.path(),"write",json!({"path":"root.rs","content":"bad","__contract":{"kind":"investigate","evidenceRequired":[{"artifact":"evidence/report","note":"why"}]}}));assert_eq!(no["ok"],false);assert_eq!(invoke(d.path(),"write",json!({"path":"evidence/report","content":"facts","__contract":{"kind":"investigate","evidenceRequired":[{"artifact":"evidence/report","note":"why"}]}}))["ok"],true);}
#[test]fn malformed_materialization_history_is_rejected_read_only(){let d=repo();sandbox::fork(d.path(),"agent/test","main",&json!({})).unwrap();journal::append(d.path(),"agent/test",json!({"t":"mat/sync","to":1,"paths":["a","a"],"hashes":["",""]})).unwrap();let before=fs::read(d.path().join(".fugue/log/agent/test.jsonl")).unwrap();assert!(sandbox::verify(d.path(),"agent/test").is_err());assert_eq!(before,fs::read(d.path().join(".fugue/log/agent/test.jsonl")).unwrap());}
#[test]fn layout_reserved_identities_cannot_collide_with_other_sandboxes(){let d=repo();for w in ["agent/test/merged","agent/test/cache","agent/test/exec-1","stage-9"]{assert!(sandbox::fork(d.path(),w,"main",&json!({})).is_err());assert!(sandbox::dispose(d.path(),w).is_err());}}
#[test]fn dispose_reclaims_abandoned_execution_and_fork_stages(){let d=repo();sandbox::fork(d.path(),"agent/test","main",&json!({})).unwrap();let mat=d.path().join(".fugue/mat/agent/test");for p in ["exec-orphan","stage-orphan"]{fs::create_dir(mat.join(p)).unwrap();fs::write(mat.join(p).join("file"),"orphan").unwrap();}sandbox::dispose(d.path(),"agent/test").unwrap();assert!(fs::read_dir(&mat).unwrap().next().is_none());}
#[test]fn fork_preserves_clean_source_file_mtime_and_validates_materialization_features(){let d=repo();let before=fs::metadata(d.path().join("root.rs")).unwrap();let f=sandbox::fork(d.path(),"agent/test","main",&json!({})).unwrap();let after=fs::metadata(Path::new(f["merged"].as_str().unwrap()).join("root.rs")).unwrap();assert_eq!(before.mtime(),after.mtime());assert_eq!(before.mtime_nsec(),after.mtime_nsec());assert_eq!(f["laid"]["mtimePreserved"],2);assert_eq!(sandbox::fork(d.path(),"agent/test","main",&json!({"strategy":"hardlink-ro","ro":"src"})).unwrap()["strategy"],"hardlink-ro");assert!(sandbox::fork(d.path(),"agent/test","main",&json!({"changeDetector":"unsafe"})).is_err());assert!(sandbox::ensure(d.path(),"agent/test",Some(999)).is_err());}
#[test]fn holder_cannot_checkpoint_or_reclaim_code_before_approval(){let d=repo();let before=fugue::git::Git::open(d.path()).unwrap().resolve("main").unwrap();let r=invoke(d.path(),"checkpoint",json!({"message":"premature","__holder":true}));assert_eq!(r["ok"],false);assert_eq!(before,fugue::git::Git::open(d.path()).unwrap().resolve("main").unwrap());fs::write(d.path().join(".fugue/config"),br#"{"actions":{"generate":{"argv":["true"],"outputs":["src"]}}}"#).unwrap();let r=invoke(d.path(),"run_action",json!({"action":"generate","__holder":true}));assert_eq!(r["ok"],false);assert!(r["output"].as_str().unwrap().contains("contract write scope"));}
#[test]fn policy_default_excludes_host_private_keys_and_broad_opt(){let d=repo();let p=sandbox::policy(d.path(),None,&json!({})).unwrap();let roots=p["reach"]["roRoots"].as_array().unwrap();assert!(!roots.iter().any(|p|p=="/opt"||p=="/etc/ssl"||p=="/etc/ssl/private"));assert!(roots.iter().any(|p|p=="/etc/ssl/certs"));for bad in ["/etc/ssl","/etc/ssl/private","/opt","/home","/"]{fs::write(d.path().join(".fugue/config"),serde_json::to_vec(&json!({"boundary":{"reach":[bad]}})).unwrap()).unwrap();assert!(sandbox::policy(d.path(),None,&json!({})).is_err(),"accepted credential/broad reach {bad}");}}
