//! Bounded serialization and storage preflight must fail before lasting effects.
use fugue::{config,util};use serde_json::json;use std::fs;
#[test]fn oversized_configuration_input_creates_no_storage(){let d=tempfile::tempdir().unwrap();assert!(config::set(d.path(),"round.goal",&"x".repeat(1024*1024+1),false).is_err());assert!(!d.path().join(".fugue").exists());}
#[test]fn expanded_configuration_serialization_preserves_previous_bytes(){let d=tempfile::tempdir().unwrap();config::set(d.path(),"round.id","r1",false).unwrap();let cfg=d.path().join(".fugue/config");let history=d.path().join(".fugue/config-history");let before=fs::read(&cfg).unwrap();let prior=fs::read(&history).unwrap();assert!(config::set(d.path(),"round.goal",&json!("x".repeat(1024*1024-4)).to_string(),false).is_err());assert_eq!(fs::read(cfg).unwrap(),before);assert_eq!(fs::read(history).unwrap(),prior);}
#[test]fn hardlinked_and_fifo_operation_locks_are_refused(){let d=tempfile::tempdir().unwrap();let p=d.path().join("operation.lock");fs::write(&p,b"unchanged").unwrap();fs::hard_link(&p,d.path().join("alias")).unwrap();assert!(util::FileLock::take(&p).is_err());assert_eq!(fs::read(p).unwrap(),b"unchanged");let fifo=d.path().join("fifo");let name=std::ffi::CString::new(fifo.to_str().unwrap()).unwrap();assert_eq!(unsafe{libc::mkfifo(name.as_ptr(),0o600)},0);assert!(util::FileLock::take(&fifo).is_err());}
#[test]fn canonical_serializer_rejects_total_node_exhaustion(){let block=json!(vec![serde_json::Value::Null;600000]);assert!(util::canonical(&json!([block.clone(),block])).is_err());}
#[test]fn canonical_serializer_enforces_escaped_byte_budget_and_utf16_order(){let bomb=json!("\0".repeat(util::MAX_BYTES/6+1));assert!(util::canonical(&bomb).is_err());let v=json!({"\u{e000}":-0.0,"😀":"a\nb","tiny":0.0000001});assert_eq!(util::canonical(&v).unwrap(),"{\"tiny\":1e-7,\"😀\":\"a\\nb\",\"\u{e000}\":0}");}

#[test]fn merged_journal_counts_partial_tails_toward_aggregate_budget(){let d=tempfile::tempdir().unwrap();let log=d.path().join(".fugue/log");fs::create_dir_all(&log).unwrap();for w in ["a","b"]{let p=log.join(format!("{w}.jsonl"));fs::File::create(p).unwrap().set_len((util::MAX_BYTES/2+1)as u64).unwrap();assert!(fugue::journal::read(d.path(),w).unwrap().is_empty());}assert!(fugue::journal::merged(d.path()).is_err());}

#[test]fn recursive_virtual_paths_are_bounded_before_storage(){let shallow=std::iter::repeat_n("a",128).collect::<Vec<_>>().join("/");let deep=format!("{shallow}/b");assert!(util::ident(&shallow).is_ok());assert!(util::rel(&shallow).is_ok());assert!(util::ident(&deep).is_err());assert!(util::rel(&deep).is_err());let d=tempfile::tempdir().unwrap();assert!(fugue::journal::append(d.path(),&deep,json!({"t":"signal"})).is_err());assert!(!d.path().join(".fugue").exists());}

#[test]fn exclusive_directory_creation_never_reuses_evidence_or_follows_parent_links(){let d=tempfile::tempdir().unwrap();let p=d.path().join("dump/call-0001");util::mkdir_new_secure(&p).unwrap();fs::write(p.join("request.json"),b"immutable evidence").unwrap();assert!(util::mkdir_new_secure(&p).is_err());assert_eq!(fs::read(p.join("request.json")).unwrap(),b"immutable evidence");let outside=tempfile::tempdir().unwrap();std::os::unix::fs::symlink(outside.path(),d.path().join("escape")).unwrap();assert!(util::mkdir_new_secure(&d.path().join("escape/call")).is_err());assert!(fs::read_dir(outside.path()).unwrap().next().is_none());}

#[test]fn invalid_directory_traversal_refuses_before_creating_prefixes(){let d=tempfile::tempdir().unwrap();assert!(util::atomic_write(&d.path().join("new/../escape/file"),b"refuse").is_err());assert!(!d.path().join("new").exists());assert!(util::mkdir_new_secure(&d.path().join("new/../evidence/call")).is_err());assert!(!d.path().join("new").exists());}

#[test]fn configuration_depth_cannot_poison_future_reads_or_history(){let d=tempfile::tempdir().unwrap();let key=format!("round.{}goal","nested.".repeat(150));assert!(config::set(d.path(),&key,"text",false).is_err());assert!(!d.path().join(".fugue").exists());config::set(d.path(),"round.id","r1",false).unwrap();let p=d.path().join(".fugue/config");let h=d.path().join(".fugue/config-history");let before=fs::read(&p).unwrap();let old=fs::read(&h).unwrap();let mut value=json!(0);for _ in 0..100{value=json!({"nested":value});}let key=format!("round.{}goal","nested.".repeat(50));assert!(config::set(d.path(),&key,&value.to_string(),false).is_err());assert_eq!(fs::read(p).unwrap(),before);assert_eq!(fs::read(h).unwrap(),old);assert_eq!(config::read(d.path()).unwrap()["round"]["id"],"r1");}

#[test]fn missing_mutation_leaf_refuses_before_any_parent_creation(){let d=tempfile::tempdir().unwrap();let p=d.path().join("new/..");assert!(util::atomic_write(&p,b"x").is_err());assert!(!d.path().join("new").exists());assert!(util::mkdir_new_secure(&p).is_err());assert!(!d.path().join("new").exists());assert!(util::FileLock::take(&p).is_err());assert!(!d.path().join("new").exists());assert!(util::replace_leaf(&p,Some(&util::Leaf{mode:0o100644,bytes:b"x".to_vec()})).is_err());assert!(!d.path().join("new").exists());}
